"""SAMBANGGOLD brand: one place for the name, the tokens and every user-facing string.

Mirrors ``src/config/brand.ts`` and ``messages/{ms,en}.json`` in the website repo
so the dashboard, the bot and the site read as one product. Bahasa Melayu is the
default; English is the second language. Product names, rank names and brand
names stay untranslated — only the surrounding words change.
"""

BRAND = {
    "name": "SAMBANGGOLD",
    "short": "SBG",
    "person": "Sam",
    "since": 2022,
    "tagline": {"ms": "Alat emas, telus.", "en": "Gold tools, transparent."},
    "group": "Sam Flip Seribu",
}

# Sam's palette, verbatim from the website's globals.css.
TOKENS = {
    "bg": "#050505", "surface": "#0b0e14", "surface2": "#11151d", "border": "#1e2330",
    "fg": "#f3f4f6", "muted": "#9aa3b2", "gold": "#d4af37", "gold2": "#f5d76e",
    "gold_deep": "#7a4003", "win": "#00c46a", "loss": "#ff4d4f", "chrome": "#b7c0ce",
    "graphite": "#050609",
}

# Rank vocabulary from the website: Awam (public) → General (free) → A-Team → Rambo.
RANKS = {
    "public": {"ms": "Awam", "en": "Public"},
    "free": {"ms": "General", "en": "General"},
    "pro": {"ms": "A-Team", "en": "A-Team"},
    "elite": {"ms": "Rambo", "en": "Rambo"},
}

LANGS = ("ms", "en")
DEFAULT_LANG = "ms"

STRINGS = {
    "ms": {
        # nav
        "nav.products": "Produk", "nav.dashboard": "Dashboard", "nav.account": "Akaun",
        "nav.signin": "Log masuk", "nav.signout": "Log keluar", "nav.admin": "Admin",
        "nav.cta": "Buka bot", "nav.lang": "EN",
        # landing
        "hero.badge": "Sejak {since} · SAMBANGGOLD · 18 alat emas",
        "hero.title": "Alat emas, telus.", "hero.title2": "Dua permukaan.",
        "hero.subtitle": "Setiap alat menjawab di Telegram dan mempunyai halaman sendiri di sini. Satu akaun Telegram menyambungkan kedua-duanya. Semua ada tier percuma, tiada yang dikunci di pintu.",
        "hero.cta_primary": "Buka bot Telegram", "hero.cta_secondary": "Lihat semua alat",
        "hero.note": "Pendidikan sahaja. Bukan nasihat kewangan.",
        "stats.products": "Alat", "stats.live": "Sudah hidup", "stats.free": "Tier percuma", "stats.since": "Sejak",
        "doors.title": "Dua cara guna", "doors.subtitle": "Sama alat, sama tier percuma. Pilih di mana anda mahu jawapan itu sampai.",
        "doors.a_title": "🤖 Di Telegram", "doors.a_body": "Satu arahan, satu jawapan. Alert masuk terus ke chat anda.", "doors.a_cta": "Buka bot",
        "doors.b_title": "🌐 Di dashboard", "doors.b_body": "Sejarah, tetapan, eksport CSV. Semua yang chat tak boleh simpan.", "doors.b_cta": "Log masuk",
        "grid.title": "Lapan belas alat", "grid.subtitle": "Sembilan sudah hidup. Sembilan lagi dalam giliran — spesifikasi ditulis, halaman ditempah.",
        "grid.live": "Hidup", "grid.queued": "Giliran", "grid.open": "Buka",
        "faq.title": "Soalan lazim",
        "faq.q1": "Perlu bayar ke?", "faq.a1": "Tidak. Setiap alat ada tier percuma yang berfungsi sepenuhnya. Tier berbayar jual skala dan automasi sahaja.",
        "faq.q2": "Kenapa perlu akaun Telegram?", "faq.a2": "Supaya alert dari bot dan sejarah di dashboard adalah satu senarai. Boleh juga daftar dengan emel dan pautkan Telegram kemudian.",
        "faq.q3": "Data harga dari mana?", "faq.a3": "Binance PAXGUSDT (bid dan ask sebenar) dengan Yahoo Finance GC=F sebagai sandaran. Kedua-duanya percuma dan awam.",
        "faq.q4": "Ini nasihat kewangan?", "faq.a4": "Bukan. Semua ini untuk pendidikan. Sahkan setiap harga dengan broker anda sendiri.",
        # sign-in
        "signin.title": "Log masuk", "signin.subtitle": "Telegram, emel, atau Google. Tiada kata laluan.",
        "signin.telegram": "Log masuk dengan Telegram", "signin.telegram_hint": "Butang ini ingat akaun Telegram terakhir. Untuk tukar: app Telegram → Tetapan → Privasi & Keselamatan → Laman web → putuskan sambungan.",
        "signin.email_label": "Emel anda", "signin.email_cta": "Hantar kod 8 digit",
        "signin.email_hint": "Kami hantar kod 8 digit ke emel anda. Sah selama 10 minit.",
        "signin.google": "Teruskan dengan Google", "signin.google_soon": "Akan datang",
        "signin.or": "atau",
        "verify.title": "Semak emel anda", "verify.subtitle": "Kod 8 digit dihantar ke {email}.",
        "verify.code_label": "Kod", "verify.cta": "Sahkan & masuk", "verify.resend": "Hantar semula",
        "verify.wrong": "Kod salah atau sudah tamat. Cuba lagi.", "verify.too_many": "Terlalu banyak cubaan. Minta kod baharu.",
        "verify.cooldown": "Tunggu seminit sebelum minta kod baharu.", "verify.bad_email": "Emel tidak sah.",
        "verify.mail_down": "Emel tidak dapat dihantar buat masa ini. Guna Telegram, atau cuba sebentar lagi.",
        "verify.sent": "Kod dihantar.", "verify.dev_code": "Mod dev — kod anda: {code}",
        "google.title": "Google — akan datang", "google.body": "Log masuk Google sedang disediakan. Guna Telegram atau emel buat masa ini.",
        # dashboard
        "dash.title": "Dashboard ahli", "dash.subtitle": "Alat anda, alert anda, rekod anda.",
        "dash.rank": "Pangkat semasa", "dash.member_since": "Ahli sejak", "dash.upgrade": "Naik ke A-Team untuk automasi",
        "dash.alerts": "Alert aktif", "dash.triggers": "Alert dicetus", "dash.saved": "Perbandingan disimpan", "dash.linked": "Telegram dipautkan",
        "dash.live": "Alat hidup", "dash.queued": "Dalam giliran", "dash.open": "Buka alat",
        "dash.link_tg": "Pautkan Telegram supaya alert masuk ke chat anda.", "dash.link_email": "Tambah emel supaya anda boleh log masuk tanpa Telegram.",
        "dash.not_linked": "Belum dipautkan",
        # account
        "account.title": "Akaun", "account.email": "Emel", "account.telegram": "Telegram", "account.lang": "Bahasa",
        "account.none": "Tiada", "account.signout": "Log keluar", "account.admin": "Anda admin. Semua ciri terbuka.",
        # admin
        "admin.title": "Admin", "admin.subtitle": "Setiap akaun, emel dan pautan Telegram.",
        "admin.users": "Akaun", "admin.emails": "Dengan emel", "admin.telegrams": "Dengan Telegram", "admin.starts": "Bot /start",
        "admin.export": "Eksport CSV", "admin.col_email": "Emel", "admin.col_tg": "Telegram", "admin.col_name": "Nama",
        "admin.col_lang": "Bahasa", "admin.col_created": "Daftar", "admin.col_last": "Log masuk akhir",
        # product page
        "product.bot_half": "Separuh Telegram", "product.web_half": "Separuh dashboard", "product.free": "Tier percuma",
        "product.live_note": "Hidup di bawah — nombor yang sama bot berikan.",
        "product.soon": "Panel akan hidup apabila setiap paparan disambung ke data.",
        "product.queued": "Dalam giliran — spesifikasi ditulis, permukaan ditempah.",
        "product.upsell": "Naik taraf", "product.upsell_note": "Tier berbayar jual skala dan automasi sahaja, bukan akses asas.",
        "product.back": "Semua alat", "product.signin": "Log masuk untuk simpan dan eksport.",
        # footer
        "footer.legal": "Undang-undang", "footer.risk": "Pendedahan risiko", "footer.rights": "Untuk pendidikan sahaja. Bukan nasihat kewangan.",
        "risk.strip": "Dagangan emas, forex dan CFD secara margin melibatkan risiko yang tinggi dan anda boleh kehilangan lebih daripada deposit awal. Prestasi lepas bukan petunjuk prestasi akan datang. Semua kandungan adalah untuk tujuan pendidikan sahaja dan bukan nasihat kewangan. Sahkan setiap harga dengan broker anda.",
        # email
        "mail.subject": "Kod log masuk {brand} anda: {code}",
        "mail.body": "Kod log masuk anda: {code}\n\nSah selama 10 minit. Jika anda tidak minta kod ini, abaikan emel ini.\n\n{brand} · Pendidikan sahaja. Bukan nasihat kewangan.",
        # bot
        "bot.pick_lang": "🌐 Pilih bahasa / Choose your language:",
        "bot.lang_set": "Bahasa ditukar ke Bahasa Melayu.",
        "bot.welcome": "<b>{brand}</b>. 18 alat emas, setiap satu menjawab di sini dan di dashboard.\n\nSemua ada tier percuma. Tiada yang dikunci di pintu.\n\n⚠️ Dagangan CFD berisiko tinggi. Pendidikan sahaja, bukan nasihat kewangan.",
        "bot.menu": "Apa yang anda mahu buat?",
        "bot.btn_tools": "🥇 Cuba alat percuma", "bot.btn_dash": "🌐 Buka dashboard", "bot.btn_faq": "❓ Soalan lazim",
        "bot.btn_channel": "📢 Channel awam", "bot.btn_back": "⬅️ Kembali", "bot.btn_menu": "⬅️ Menu Utama",
        "bot.btn_try": "▶️ Cuba contoh", "bot.btn_open": "🌐 Buka di dashboard", "bot.btn_share": "📤 Kongsi", "bot.btn_again": "🔁 Cuba lagi",
        "bot.btn_more": "🔮 Lihat yang dalam giliran",
        "bot.tools": "<b>Alat yang sudah hidup</b>\nPilih satu. Setiap satu percuma.",
        "bot.queued": "<b>Dalam giliran</b>\nSpesifikasi ditulis, halaman ditempah. Bot akan jawab bila hidup.",
        "bot.tool_card": "{emoji} <b>{name}</b>\n{solution}\n\n<b>Tier percuma:</b> {free}\n<b>Arahan:</b> <code>{command}</code>",
        "bot.faq": "<b>Soalan lazim</b>\n\n<b>Perlu bayar ke?</b> Tidak. Setiap alat ada tier percuma yang berfungsi sepenuhnya.\n\n<b>Kenapa Telegram?</b> Supaya alert di sini dan sejarah di dashboard adalah satu senarai.\n\n<b>Data harga?</b> Binance PAXGUSDT, sandaran Yahoo GC=F. Percuma dan awam.\n\n<b>Nasihat kewangan?</b> Bukan. Pendidikan sahaja.",
        "bot.help": "<b>Arahan</b>", "bot.help_tail": "/start — menu · /language — tukar bahasa · /dashboard — pautan dashboard\n\nPendidikan sahaja. Bukan nasihat kewangan.",
        "bot.dash": "Dashboard anda. Log masuk dengan Telegram — akaun yang sama, senarai alert yang sama.",
        "bot.unknown": "Arahan tak dikenali. Hantar /start untuk menu.",
        "bot.queued_reply": "{emoji} <b>{name}</b> — dalam giliran.\n{solution}",
        "bot.result_tail": "Simpan, eksport dan bandingkan di dashboard.",
        "bot.share_text": "Saya guna {brand} untuk emas. Cuba percuma:",
        # calendar
        "cal.title": "📅 <b>Kalendar emas</b>",
        "cal.next": "Acara USD merah seterusnya", "cal.none": "Tiada acara merah dalam suapan minggu ini.",
        "cal.fomc": "FOMC seterusnya", "cal.holiday": "Cuti CME seterusnya", "cal.season": "Bulan ini (purata {n} tahun)",
        "cal.season_line": "pulangan {ret:+.1f}% · julat {rng:.1f}%",
        "cal.on": "🔔 Alert 30 minit sebelum: <b>HIDUP</b>", "cal.off": "🔕 Alert 30 minit sebelum: <b>MATI</b>",
        "cal.btn_on": "🔔 Hidupkan alert", "cal.btn_off": "🔕 Matikan alert",
        "cal.push": "⏰ <b>{title}</b> dalam 30 minit ({when} MYT).\nSpread biasanya melebar. Pendidikan sahaja.",
        "cal.need_chat": "Alert perlukan chat Telegram. Buka bot dan hantar /calendar_alert.",
        "cal.spread_note": "Spread diukur setiap 5 minit; sejarah setiap acara terkumpul dari sini.",

        # sign-in extras
        "signin.no_username": "Butang Telegram akan muncul sebaik TELEGRAM_BOT_USERNAME ditetapkan pada pelayan.",
        # #1 bot replies
        "watch.usage": "Guna:\n<code>/watch XAUUSD</code> — harga langsung, spread dan paras entry/stop\n<code>/watch XAUUSD above 2450</code> — alert bila <i>ask</i> sampai 2450\n<code>/watch XAUUSD below 2380</code> — alert bila <i>bid</i> jatuh ke 2380\n<code>/watch list</code> · <code>/watch clear</code>\n\nAtau tekan ▶️ Mula dan bot akan tanya satu-satu.",
        "watch.none": "Tiada alert dipasang.", "watch.list": "<b>Alert dipasang</b>", "watch.cleared": "{n} alert dibuang.",
        "watch.only_gold": "Emas sahaja buat masa ini (<code>XAUUSD</code>). Berbilang pasangan ada di tier PRO.",
        "watch.feed_down": "Suapan harga tak tersedia sekarang ({err}). Cuba lagi seminit.",
        "watch.armed": "Dipasang: ", "watch.level_num": "Paras mesti nombor.", "watch.need_chat": "Alert perlukan chat Telegram untuk dihantar.",
        "watch.ok": "✅ Alert #{id} dipasang: {sym} {dir} {level} (cetus pada {side}).\nSekarang: bid {bid} · ask {ask}",
        "watch.spread": "Spread {spread} · {src}", "watch.nobook": "n/a (tiada order book)",
        "watch.long": "Long: masuk {e}, stop {s}", "watch.short": "Short: masuk {e}, stop {s}",
        "watch.above": "naik melepasi", "watch.below": "turun bawah",
        "watch.d_armed": "Alert #{id} dipasang.", "watch.d_updated": "Paras dikemas kini.", "watch.d_disarmed": "Alert dibuang.",
        "watch.fire": "🔔 <b>XAUUSD {dir} {level}</b> — {side} sekarang {price} ({src})\nPendidikan sahaja. Sahkan dengan broker anda.",
        # #3 #8 bot replies
        "prop.usage": "Guna: <code>/propcalc YURAN SAIZ LULUS%</code>\nContoh: <code>/propcalc 500 100000 15</code> — yuran $500 pada akaun $100k dengan 15% peluang lulus.\n\nAtau tekan ▶️ Mula dan bot akan tanya satu-satu.",
        "prop.reply": "{tone} <b>EV {ev}</b> atas yuran {cost} ({roi} ROI)\nPayout pertama jika funded: {payout} (sasaran {target} × pembahagian {split} pada {size})\nKadar lulus pulang modal: <b>{be}</b> — anda kata {pass}\n\nTampal terma firm di dashboard untuk imbasan peraturan.",
        "ib.usage": "Guna: <code>/ibcalc LOT KADAR [KLIEN] [CLAWBACK%]</code>\nContoh: <code>/ibcalc 40 7 25 5</code> — 25 klien trade 40 lot sebulan pada $7 setiap lot dengan 5% clawback.\n\nAtau tekan ▶️ Mula dan bot akan tanya satu-satu.",
        "ib.reply": "<b>{net} bersih sebulan</b> · {annual} setahun\nKasar {gross} dari {clients} klien × {lots:g} lot × ${rate:g}\nClawback {claw} · margin {margin}\n\nTambah kos pematuhan, ambang payout dan tempoh pegangan di dashboard untuk lihat bila tunai pertama masuk.",
        # guided flows
        "flow.start": "▶️ Mula", "flow.example": "💡 Contoh", "flow.cancel": "✖ Batal", "flow.skip": "⏭ Langkau",
        "flow.cancelled": "Dibatalkan. Hantar /start untuk menu.", "flow.not_number": "Nombor sahaja, contoh <code>2450</code>. Cuba lagi.",
        "flow.chosen": "{prompt}\n\n✅ {value}", "flow.typed": "Atau taip nilai anda sendiri.",
        "flow.watch_mode": "🥇 <b>Gold Watch</b>\nApa yang anda mahu?",
        "flow.watch_price": "📈 Harga sekarang", "flow.watch_above": "🔔 Alert bila naik melepasi…", "flow.watch_below": "🔔 Alert bila turun bawah…",
        "flow.watch_level": "Masukkan paras harga (contoh <code>2450</code>).",
        "flow.prop_fee": "🏛 <b>Prop Firm Challenge</b>\nYuran challenge (USD)?",
        "flow.prop_size": "Saiz akaun (USD)?", "flow.prop_pass": "Peluang anda lulus (%)? Industri: 10–25%.",
        "flow.ib_lots": "🥇 <b>IB Revenue</b>\nLot setiap klien sebulan?", "flow.ib_rate": "Rebate (USD) setiap lot?",
        "flow.ib_clients": "Berapa klien aktif?", "flow.ib_claw": "Clawback (%)?",
        "flow.audit_handle": "🔒 <b>Bot Scam Detector</b>\nHantar username bot itu (contoh <code>@wallet_verify_b0t</code>).",
        "flow.audit_text": "Tampal apa yang bot itu kata — atau Langkau.",
        "flow.copy_broker": "🔒 <b>Copy-Trade Audit</b>\nBroker mana? Pilih atau taip nama.",
        "flow.copy_spread": "Spread biasa (pip)? Atau Langkau.", "flow.copy_lots": "Lot yang anda copy sebulan? Atau Langkau.",
        "flow.scan_text": "💱 <b>Red-Flag Scanner</b>\nTampal pitch signal itu di sini — post channel, DM, atau halaman jualan.",
        "flow.inf_handle": "🔒 <b>Influencer Audit</b>\nHandle influencer itu (contoh <code>@gold_guru</code>)?",
        "flow.inf_text": "Tampal post, bio atau DM mereka, termasuk pautan — atau Langkau.",
        # dashboard tool panels
        "ui.calc": "Kira", "ui.calc_save": "Kira & simpan", "ui.verdict": "Verdict", "ui.rule": "Peraturan", "ui.where": "Di mana",
        "ui.why": "Kenapa penting", "ui.flag": "Bendera", "ui.history": "Sejarah", "ui.when": "Bila (UTC)", "ui.source": "Sumber",
        "ui.price": "Harga", "ui.never": "tak pernah", "ui.month": "Bulan", "ui.event": "Acara", "ui.forecast": "Ramalan", "ui.previous": "Sebelum",
        "ui.w_live": "Emas langsung", "ui.w_mid": "XAUUSD tengah", "ui.w_bidask": "Bid / ask", "ui.w_bidask_note": "harga sebenar yang anda dapat",
        "ui.w_nobook": "tiada order book pada sumber ini", "ui.w_peroz": "seauns", "ui.w_stopnote": "Stop 0.5% dilebarkan mengikut spread — titik mula, bukan signal.",
        "ui.w_feed_err": "Suapan tak tersedia: {err}", "ui.w_armed": "Alert dipasang",
        "ui.w_signin": "Log masuk dengan Telegram (atas kanan) untuk lihat alert yang anda pasang di bot, ubah paras dan eksport sejarah. Satu akaun, dua permukaan.",
        "ui.w_dir": "Arah", "ui.w_above": "naik melepasi — cetus pada ask", "ui.w_below": "turun bawah — cetus pada bid", "ui.w_level": "Paras",
        "ui.w_arm": "Pasang alert", "ui.w_pair": "Pasangan", "ui.w_save": "Simpan", "ui.w_disarm": "Buang",
        "ui.w_none": "Tiada alert. Pasang di sini atau hantar <code>/watch XAUUSD above 2450</code> ke bot — senarai yang sama.",
        "ui.w_hist": "Sejarah alert", "ui.w_fired": "Dicetus (UTC)", "ui.w_alert": "Alert", "ui.w_export": "⬇ Eksport sejarah (.csv)",
        "ui.w_nohist": "Belum ada cetusan. Setiap satu direkod dengan harga dan spread ketika itu — jurnal yang chat tak boleh beri.",
        "ui.p_calc": "Kalkulator", "ui.p_firm": "Firm", "ui.p_fee": "Yuran challenge $", "ui.p_size": "Saiz akaun $", "ui.p_pass": "Peluang lulus anda %",
        "ui.p_target": "Sasaran untung %", "ui.p_split": "Pembahagian untung %", "ui.p_resets": "Reset dibeli", "ui.optional": "pilihan",
        "ui.p_ev": "Expected value", "ui.p_on_paid": "{roi} atas {cost} dibayar", "ui.p_breakeven": "Kadar lulus pulang modal", "ui.p_entered": "anda masukkan {p}",
        "ui.p_first": "Payout pertama jika funded", "ui.p_target_split": "sasaran {target} × pembahagian {split}",
        "ui.p_share": "Pautan kongsi untuk keputusan ini ialah bar alamat. Kadar lulus industri sekitar 10–25%; jika pulang modal anda di atas julat itu, yuran itu tak berpihak kepada anda.",
        "ui.p_scan": "Imbasan peraturan", "ui.p_paste": "Tampal terma challenge", "ui.p_paste_ph": "Tampal halaman peraturan atau T&C firm di sini…", "ui.p_scan_btn": "Imbas terma",
        "ui.p_reds": "{r} merah · {y} kuning", "ui.p_chars": "{n} aksara diimbas", "ui.why_fail": "Kenapa ia gagalkan orang",
        "ui.p_clean": "Tiada peraturan gagal yang dikenali sepadan. Itu bukan bil bersih — baca bahagian drawdown sendiri.",
        "ui.p_saved": "Perbandingan disimpan", "ui.paid": "Dibayar", "ui.size": "Saiz", "ui.pass": "Lulus", "ui.breakeven": "Pulang modal",
        "ui.p_nosave": "Belum ada yang disimpan. Guna <em>Kira & simpan</em> untuk banding firm sebelah-menyebelah. Perbandingan kekal dalam sesi pelayar ini.",
        "ui.i_model": "Model hasil", "ui.i_broker": "Broker", "ui.i_lots": "Lot setiap klien / bulan", "ui.i_rate": "Rebate $ setiap lot", "ui.i_clients": "Klien aktif",
        "ui.i_claw": "Clawback %", "ui.i_comp": "Kos pematuhan $ / bulan", "ui.i_thresh": "Ambang payout $", "ui.i_hold": "Tempoh pegangan (hari)",
        "ui.i_net": "Bersih sebulan", "ui.i_net_note": "{annual} setahun · margin {margin}", "ui.i_gross": "Rebate kasar", "ui.i_gross_note": "−{claw} clawback · −{comp} pematuhan",
        "ui.i_first": "Tunai pertama masuk", "ui.i_day": "hari {d}", "ui.i_first_note": "ambang {thresh} + pegangan {days} hari",
        "ui.i_timeline": "Garis masa payout", "ui.earned": "Diperoleh", "ui.paid_out": "Dibayar", "ui.held": "Ditahan", "ui.cumulative": "Kumulatif dibayar",
        "ui.i_share": "Pautan kongsi untuk model ini: bar alamat. Ambang payout dan tempoh pegangan ialah dua nombor yang perlu disahkan secara bertulis sebelum anda rujuk seorang klien pun.",
        "ui.i_checklist": "Senarai semak pematuhan", "ui.i_download": "⬇ Muat turun senarai semak (.txt)", "ui.i_saved": "Senario disimpan",
        "ui.rate": "Kadar", "ui.clients": "Klien", "ui.net_month": "Bersih / bulan", "ui.annual": "Setahun", "ui.first_cash": "Tunai pertama",
        "ui.i_nosave": "Belum ada yang disimpan. Guna <em>Kira & simpan</em> untuk banding broker sebelah-menyebelah. Senario kekal dalam sesi pelayar ini.",
        "ui.c_baseline": "Spread asas", "ui.c_season": "Musim · 12 bulan", "ui.c_season_note": "{src} · purata pulangan bulanan; tinggi bar ialah saiz pergerakan.",
        "ui.c_hist": "Apa spread buat kali lepas", "ui.measured": "Diukur", "ui.worst": "Spread terburuk", "ui.mean": "Purata", "ui.vs_base": "vs asas",
        "ui.s_h_bot": "Audit bot", "ui.s_h_copy": "Audit broker copy-trade", "ui.s_h_scan": "Imbas pitch signal", "ui.s_h_inf": "Audit influencer",
        "ui.audit": "Audit", "ui.scan": "Imbas",
        "ui.s_ph_bot": "Tampal mesej alu-aluan bot itu, pautan yang ia hantar, atau DM…", "ui.s_ph_copy": "Tampal pitch: 'copy trade saya, 10% sebulan, daftar guna link saya…'",
        "ui.s_ph_scan": "Tampal seluruh pitch — post channel, DM, halaman jualan…", "ui.s_ph_inf": "Tampal post, bio, mesej pin atau DM mereka, termasuk pautan…",
        "ui.s_sub_bot": "Username bot", "ui.s_txt_bot": "Tampal apa yang bot itu kata (pilihan)", "ui.s_sub_copy": "Broker", "ui.s_txt_copy": "Tampal pitch copy-trade (pilihan)",
        "ui.s_sub_scan": "Channel atau penjual (pilihan)", "ui.s_txt_scan": "Tampal pitch", "ui.s_sub_inf": "Handle influencer", "ui.s_txt_inf": "Tampal post, bio atau DM mereka (pilihan)",
        "ui.s_spread": "Spread biasa (pip)", "ui.s_lots": "Lot yang anda copy sebulan", "ui.s_need_sub": "{label} diperlukan.", "ui.s_need_text": "Tampal pitch dahulu.",
        "ui.s_flags": "Bendera", "ui.s_rgy": "merah / kuning / baik", "ui.s_reg": "Lesen", "ui.s_tier1": "Tier-1", "ui.s_offshore": "Offshore sahaja", "ui.s_unknown": "Tak dikenali",
        "ui.s_not_table": "tiada dalam jadual kami", "ui.s_cost_year": "Kos spread / tahun", "ui.s_cost_note": "${m:,.0f} sebulan pada {p:g} pip × {l:g} lot",
        "ui.s_ref": "Pautan rujukan broker", "ui.s_ref_note": "mereka dibayar bila anda deposit", "ui.s_share": "Pautan kongsi", "ui.s_community": "diimbas {n}× oleh komuniti",
        "ui.s_checklist": "Senarai semak", "ui.s_verify": "Sahkan di daftar", "ui.regulator": "Regulator", "ui.meaning": "Maksudnya", "ui.register": "Daftar", "ui.open": "buka ↗",
        "ui.s_trail": "Jejak promosi broker", "ui.s_watch": "Senarai pantau", "ui.scans": "Imbasan", "ui.latest": "Skor terkini", "ui.rescan": "Imbas semula",
        "ui.s_run": "Buat imbasan anda sendiri", "ui.s_scan_n": "imbasan #{n}",
        "ui.l_title": "Templat laporan kerugian", "ui.l_lede": "Sudah rugi? Isi dan muat turun laporan dalam bentuk yang borang FTC, CFTC, IC3, SC Malaysia dan BNM minta.",
        "ui.l_handle": "Handle influencer", "ui.l_platform": "Platform", "ui.l_broker": "Broker / platform yang dipromosi", "ui.l_amount": "Jumlah rugi", "ui.l_currency": "Mata wang",
        "ui.l_date": "Tarikh", "ui.l_story": "Apa yang berlaku, mengikut urutan", "ui.l_story_ph": "Hubungan pertama, apa yang dijanjikan, apa yang anda bayar, apa jadi selepas itu…",
        "ui.l_download": "⬇ Muat turun report.txt",
        # scanners
        "scan.score": "skor", "scan.subject": "Subjek",
        "scan.verdict_high": "RISIKO TINGGI", "scan.verdict_caution": "BERHATI-HATI", "scan.verdict_low": "RISIKO RENDAH",
        "scan.more": "… {n} lagi penemuan di dashboard.", "scan.clean": "Tiada bendera dijumpai dalam teks ini. Itu bukan bukti selamat.",
        "scan.saved": "Disimpan sebagai imbasan #{n} — sejarah dan senarai pantau ada di dashboard.",
        "scan.disclaimer": "Pendidikan sahaja. Bukan nasihat kewangan.",
        "scan.usage_audit": "Guna: <code>/audit @nama_bot [apa yang bot itu kata]</code>\nContoh: <code>/audit @wallet_verify_b0t hantar seed phrase untuk claim</code>",
        "scan.usage_copy": "Guna: <code>/copyaudit BROKER [SPREAD_PIP] [LOT_SEBULAN]</code>\nContoh: <code>/copyaudit exness 2 10</code>",
        "scan.usage_scan": "Guna: <code>/scan TEKS</code> — tampal pitch signal (sekurang-kurangnya satu ayat).",
        "scan.usage_influencer": "Guna: <code>/influencer @handle [teks post atau DM]</code>",
        "scan.tail_audit": "Semak: nama berakhir 'bot', dipaut dari laman rasmi, tak pernah minta seed phrase atau yuran.",
        "scan.tail_copy": "Sahkan nombor lesen di daftar pengawal selia sebelum deposit.",
        "scan.tail_scan": "Minta akaun Myfxbook/FX Blue yang disahkan. Tangkapan skrin bukan bukti.",
        "scan.regs": "Pengawal selia dalam jadual kami: {regs}",
        "scan.cost": "Kos spread: {pips:g} pip × {lots:g} lot ≈ <b>${monthly:,.0f}/bulan</b> · ${yearly:,.0f}/tahun",
        "scan.demand": "Minta daripada mereka:",
        "scan.ib_links": "🔗 {n} pautan rujukan broker dijumpai — mereka dibayar bila anda deposit.",
    },
    "en": {
        "nav.products": "Tools", "nav.dashboard": "Dashboard", "nav.account": "Account",
        "nav.signin": "Sign in", "nav.signout": "Sign out", "nav.admin": "Admin",
        "nav.cta": "Open bot", "nav.lang": "BM",
        "hero.badge": "Since {since} · SAMBANGGOLD · 18 gold tools",
        "hero.title": "Gold tools, transparent.", "hero.title2": "Two surfaces.",
        "hero.subtitle": "Every tool answers in Telegram and has its own page here. One Telegram account links the two. All have a free tier; none is locked at the door.",
        "hero.cta_primary": "Open the Telegram bot", "hero.cta_secondary": "See every tool",
        "hero.note": "Education only. Not financial advice.",
        "stats.products": "Tools", "stats.live": "Live", "stats.free": "Free tiers", "stats.since": "Since",
        "doors.title": "Two ways to use it", "doors.subtitle": "Same tool, same free tier. Pick where you want the answer to land.",
        "doors.a_title": "🤖 In Telegram", "doors.a_body": "One command, one answer. Alerts land in your chat.", "doors.a_cta": "Open bot",
        "doors.b_title": "🌐 On the dashboard", "doors.b_body": "History, settings, CSV export. Everything a chat cannot keep.", "doors.b_cta": "Sign in",
        "grid.title": "Eighteen tools", "grid.subtitle": "Nine are live. Nine are queued — spec written, page reserved.",
        "grid.live": "Live", "grid.queued": "Queued", "grid.open": "Open",
        "faq.title": "FAQ",
        "faq.q1": "Do I have to pay?", "faq.a1": "No. Every tool has a fully working free tier. Paid tiers sell scale and automation only.",
        "faq.q2": "Why a Telegram account?", "faq.a2": "So bot alerts and dashboard history are one list. You can also sign up by email and link Telegram later.",
        "faq.q3": "Where does the price come from?", "faq.a3": "Binance PAXGUSDT (real bid and ask) with Yahoo Finance GC=F as fallback. Both free and public.",
        "faq.q4": "Is this financial advice?", "faq.a4": "No. Education only. Verify every price with your own broker.",
        "signin.title": "Sign in", "signin.subtitle": "Telegram, email, or Google. No password.",
        "signin.telegram": "Sign in with Telegram", "signin.telegram_hint": "This button remembers the last Telegram account. To switch: Telegram app → Settings → Privacy & Security → Websites → disconnect this site.",
        "signin.email_label": "Your email", "signin.email_cta": "Send 8-digit code",
        "signin.email_hint": "We email you an 8-digit code. Valid for 10 minutes.",
        "signin.google": "Continue with Google", "signin.google_soon": "Coming soon",
        "signin.or": "or",
        "verify.title": "Check your email", "verify.subtitle": "An 8-digit code was sent to {email}.",
        "verify.code_label": "Code", "verify.cta": "Verify & enter", "verify.resend": "Resend",
        "verify.wrong": "Wrong or expired code. Try again.", "verify.too_many": "Too many attempts. Request a new code.",
        "verify.cooldown": "Wait a minute before requesting another code.", "verify.bad_email": "Invalid email.",
        "verify.mail_down": "Email cannot be sent right now. Use Telegram, or try again shortly.",
        "verify.sent": "Code sent.", "verify.dev_code": "Dev mode — your code: {code}",
        "google.title": "Google — coming soon", "google.body": "Google sign-in is being set up. Use Telegram or email for now.",
        "dash.title": "Member dashboard", "dash.subtitle": "Your tools, your alerts, your record.",
        "dash.rank": "Current rank", "dash.member_since": "Member since", "dash.upgrade": "Move up to A-Team for automation",
        "dash.alerts": "Armed alerts", "dash.triggers": "Alerts fired", "dash.saved": "Saved comparisons", "dash.linked": "Telegram linked",
        "dash.live": "Live tools", "dash.queued": "Queued", "dash.open": "Open tool",
        "dash.link_tg": "Link Telegram so alerts land in your chat.", "dash.link_email": "Add an email so you can sign in without Telegram.",
        "dash.not_linked": "Not linked",
        "account.title": "Account", "account.email": "Email", "account.telegram": "Telegram", "account.lang": "Language",
        "account.none": "None", "account.signout": "Sign out", "account.admin": "You are admin. Every feature is open.",
        "admin.title": "Admin", "admin.subtitle": "Every account, email and Telegram link.",
        "admin.users": "Accounts", "admin.emails": "With email", "admin.telegrams": "With Telegram", "admin.starts": "Bot /start",
        "admin.export": "Export CSV", "admin.col_email": "Email", "admin.col_tg": "Telegram", "admin.col_name": "Name",
        "admin.col_lang": "Lang", "admin.col_created": "Joined", "admin.col_last": "Last sign-in",
        "product.bot_half": "Telegram half", "product.web_half": "Dashboard half", "product.free": "Free tier",
        "product.live_note": "Live below — the same numbers the bot returns.",
        "product.soon": "Panels come online as each view is wired to data.",
        "product.queued": "Queued — the spec is written, the surface is reserved.",
        "product.upsell": "Upgrade", "product.upsell_note": "Paid tiers sell scale and automation only, never basic access.",
        "product.back": "All tools", "product.signin": "Sign in to save and export.",
        "footer.legal": "Legal", "footer.risk": "Risk disclosure", "footer.rights": "Education only. Not financial advice.",
        "risk.strip": "Trading gold, forex and CFDs on margin carries a high level of risk and you could lose more than your initial deposit. Past performance is not indicative of future results. All content is for education only and is not financial advice. Verify every price with your broker.",
        "mail.subject": "Your {brand} sign-in code: {code}",
        "mail.body": "Your sign-in code: {code}\n\nValid for 10 minutes. If you did not request it, ignore this email.\n\n{brand} · Education only. Not financial advice.",
        "bot.pick_lang": "🌐 Choose your language / Pilih bahasa anda:",
        "bot.lang_set": "Language set to English.",
        "bot.welcome": "<b>{brand}</b>. 18 gold tools, each answering here and on the dashboard.\n\nAll have a free tier. None is locked at the door.\n\n⚠️ CFD trading carries high risk. Education only, not financial advice.",
        "bot.menu": "What do you want to do?",
        "bot.btn_tools": "🥇 Try a free tool", "bot.btn_dash": "🌐 Open dashboard", "bot.btn_faq": "❓ FAQ",
        "bot.btn_channel": "📢 Public channel", "bot.btn_back": "⬅️ Back", "bot.btn_menu": "⬅️ Main Menu",
        "bot.btn_try": "▶️ Try an example", "bot.btn_open": "🌐 Open on dashboard", "bot.btn_share": "📤 Share", "bot.btn_again": "🔁 Try again",
        "bot.btn_more": "🔮 See what is queued",
        "bot.tools": "<b>Tools that are live</b>\nPick one. Each is free.",
        "bot.queued": "<b>Queued</b>\nSpec written, page reserved. The bot answers once each is live.",
        "bot.tool_card": "{emoji} <b>{name}</b>\n{solution}\n\n<b>Free tier:</b> {free}\n<b>Command:</b> <code>{command}</code>",
        "bot.faq": "<b>FAQ</b>\n\n<b>Do I have to pay?</b> No. Every tool has a fully working free tier.\n\n<b>Why Telegram?</b> So alerts here and history on the dashboard are one list.\n\n<b>Price data?</b> Binance PAXGUSDT, Yahoo GC=F fallback. Free and public.\n\n<b>Financial advice?</b> No. Education only.",
        "bot.help": "<b>Commands</b>", "bot.help_tail": "/start — menu · /language — switch language · /dashboard — dashboard link\n\nEducation only. Not financial advice.",
        "bot.dash": "Your dashboard. Sign in with Telegram — same account, same alert list.",
        "bot.unknown": "Unknown command. Send /start for the menu.",
        "bot.queued_reply": "{emoji} <b>{name}</b> — queued.\n{solution}",
        "bot.result_tail": "Save, export and compare on the dashboard.",
        "bot.share_text": "I use {brand} for gold. Try it free:",
        "cal.title": "📅 <b>Gold calendar</b>",
        "cal.next": "Next red USD events", "cal.none": "No red events in this week's feed.",
        "cal.fomc": "Next FOMC", "cal.holiday": "Next CME holiday", "cal.season": "This month ({n}-year average)",
        "cal.season_line": "return {ret:+.1f}% · range {rng:.1f}%",
        "cal.on": "🔔 30-minute alert: <b>ON</b>", "cal.off": "🔕 30-minute alert: <b>OFF</b>",
        "cal.btn_on": "🔔 Turn alerts on", "cal.btn_off": "🔕 Turn alerts off",
        "cal.push": "⏰ <b>{title}</b> in 30 minutes ({when} MYT).\nSpreads usually widen. Education only.",
        "cal.need_chat": "Alerts need a Telegram chat. Open the bot and send /calendar_alert.",
        "cal.spread_note": "Spread is sampled every 5 minutes; per-event history builds from here.",

        "signin.no_username": "The Telegram button appears once TELEGRAM_BOT_USERNAME is set on the server.",
        "watch.usage": "Usage:\n<code>/watch XAUUSD</code> — live price, spread and entry/stop levels\n<code>/watch XAUUSD above 2450</code> — alert when the <i>ask</i> reaches 2450\n<code>/watch XAUUSD below 2380</code> — alert when the <i>bid</i> falls to 2380\n<code>/watch list</code> · <code>/watch clear</code>\n\nOr tap ▶️ Start and the bot asks one thing at a time.",
        "watch.none": "No alerts armed.", "watch.list": "<b>Armed alerts</b>", "watch.cleared": "Cleared {n} alert(s).",
        "watch.only_gold": "Only gold for now (<code>XAUUSD</code>). Multi-pair is on the PRO tier.",
        "watch.feed_down": "Feed unavailable right now ({err}). Try again in a minute.",
        "watch.armed": "Armed: ", "watch.level_num": "Level must be a number.", "watch.need_chat": "Alerts need a Telegram chat to fire into.",
        "watch.ok": "✅ Alert #{id} armed: {sym} {dir} {level} (fires on the {side}).\nNow: bid {bid} · ask {ask}",
        "watch.spread": "Spread {spread} · {src}", "watch.nobook": "n/a (no order book)",
        "watch.long": "Long: enter {e}, stop {s}", "watch.short": "Short: enter {e}, stop {s}",
        "watch.above": "above", "watch.below": "below",
        "watch.d_armed": "Alert #{id} armed.", "watch.d_updated": "Threshold updated.", "watch.d_disarmed": "Alert disarmed.",
        "watch.fire": "🔔 <b>XAUUSD {dir} {level}</b> — {side} now {price} ({src})\nEducational research only. Verify with your broker.",
        "prop.usage": "Usage: <code>/propcalc FEE SIZE PASS%</code>\nExample: <code>/propcalc 500 100000 15</code> — a $500 fee on a $100k account with a 15% chance of passing.\n\nOr tap ▶️ Start and the bot asks one thing at a time.",
        "prop.reply": "{tone} <b>EV {ev}</b> on a {cost} fee ({roi} ROI)\nFirst payout if funded: {payout} ({target} target × {split} split on {size})\nBreakeven pass rate: <b>{be}</b> — you said {pass}\n\nPaste the firm's terms on the dashboard for the rule scan.",
        "ib.usage": "Usage: <code>/ibcalc LOTS RATE [CLIENTS] [CLAWBACK%]</code>\nExample: <code>/ibcalc 40 7 25 5</code> — 25 clients trading 40 lots a month at $7 a lot with 5% clawback.\n\nOr tap ▶️ Start and the bot asks one thing at a time.",
        "ib.reply": "<b>{net} net per month</b> · {annual} a year\nGross {gross} from {clients} client(s) × {lots:g} lots × ${rate:g}\nClawback {claw} · margin {margin}\n\nAdd compliance cost, payout threshold and hold period on the dashboard to see when the first cash lands.",
        "flow.start": "▶️ Start", "flow.example": "💡 Example", "flow.cancel": "✖ Cancel", "flow.skip": "⏭ Skip",
        "flow.cancelled": "Cancelled. Send /start for the menu.", "flow.not_number": "Numbers only, e.g. <code>2450</code>. Try again.",
        "flow.chosen": "{prompt}\n\n✅ {value}", "flow.typed": "Or type your own value.",
        "flow.watch_mode": "🥇 <b>Gold Watch</b>\nWhat do you want?",
        "flow.watch_price": "📈 Price now", "flow.watch_above": "🔔 Alert when it rises above…", "flow.watch_below": "🔔 Alert when it falls below…",
        "flow.watch_level": "Enter the price level (e.g. <code>2450</code>).",
        "flow.prop_fee": "🏛 <b>Prop Firm Challenge</b>\nChallenge fee (USD)?",
        "flow.prop_size": "Account size (USD)?", "flow.prop_pass": "Your chance of passing (%)? Industry: 10–25%.",
        "flow.ib_lots": "🥇 <b>IB Revenue</b>\nLots per client per month?", "flow.ib_rate": "Rebate (USD) per lot?",
        "flow.ib_clients": "How many active clients?", "flow.ib_claw": "Clawback (%)?",
        "flow.audit_handle": "🔒 <b>Bot Scam Detector</b>\nSend the bot's username (e.g. <code>@wallet_verify_b0t</code>).",
        "flow.audit_text": "Paste what the bot said — or Skip.",
        "flow.copy_broker": "🔒 <b>Copy-Trade Audit</b>\nWhich broker? Pick one or type the name.",
        "flow.copy_spread": "Typical spread (pips)? Or Skip.", "flow.copy_lots": "Lots you copy per month? Or Skip.",
        "flow.scan_text": "💱 <b>Red-Flag Scanner</b>\nPaste the signal pitch here — the channel post, the DM, or the sales page.",
        "flow.inf_handle": "🔒 <b>Influencer Audit</b>\nThe influencer's handle (e.g. <code>@gold_guru</code>)?",
        "flow.inf_text": "Paste their post, bio or DM, links included — or Skip.",
        "ui.calc": "Calculate", "ui.calc_save": "Calculate & save", "ui.verdict": "Verdict", "ui.rule": "Rule", "ui.where": "Where",
        "ui.why": "Why it matters", "ui.flag": "Flag", "ui.history": "History", "ui.when": "When (UTC)", "ui.source": "Source",
        "ui.price": "Price", "ui.never": "never", "ui.month": "Month", "ui.event": "Event", "ui.forecast": "Forecast", "ui.previous": "Previous",
        "ui.w_live": "Live gold", "ui.w_mid": "XAUUSD mid", "ui.w_bidask": "Bid / ask", "ui.w_bidask_note": "the prices you would actually get",
        "ui.w_nobook": "no order book on this source", "ui.w_peroz": "per oz", "ui.w_stopnote": "Stops are 0.5% widened by the spread — a starting point, not a signal.",
        "ui.w_feed_err": "Feed unavailable: {err}", "ui.w_armed": "Armed alerts",
        "ui.w_signin": "Sign in with Telegram (top right) to see the alerts you armed in the bot, edit thresholds and export history. One account, both surfaces.",
        "ui.w_dir": "Direction", "ui.w_above": "above — fires on the ask", "ui.w_below": "below — fires on the bid", "ui.w_level": "Level",
        "ui.w_arm": "Arm alert", "ui.w_pair": "Pair", "ui.w_save": "Save", "ui.w_disarm": "Disarm",
        "ui.w_none": "Nothing armed. Arm one here or send <code>/watch XAUUSD above 2450</code> to the bot — same list.",
        "ui.w_hist": "Alert history", "ui.w_fired": "Fired (UTC)", "ui.w_alert": "Alert", "ui.w_export": "⬇ Export history (.csv)",
        "ui.w_nohist": "No triggers yet. Each one is recorded with the price and spread at fire time — the journal a chat log cannot give you.",
        "ui.p_calc": "Calculator", "ui.p_firm": "Firm", "ui.p_fee": "Challenge fee $", "ui.p_size": "Account size $", "ui.p_pass": "Your pass chance %",
        "ui.p_target": "Profit target %", "ui.p_split": "Profit split %", "ui.p_resets": "Resets bought", "ui.optional": "optional",
        "ui.p_ev": "Expected value", "ui.p_on_paid": "{roi} on {cost} paid", "ui.p_breakeven": "Breakeven pass rate", "ui.p_entered": "you entered {p}",
        "ui.p_first": "First payout if funded", "ui.p_target_split": "{target} target × {split} split",
        "ui.p_share": "A shareable link to this exact result is the address bar. Industry pass rates sit around 10–25%; if your breakeven is above that band, the fee is priced against you.",
        "ui.p_scan": "Rule scan", "ui.p_paste": "Paste the challenge terms", "ui.p_paste_ph": "Paste the firm's rules page or T&Cs here…", "ui.p_scan_btn": "Scan terms",
        "ui.p_reds": "{r} red · {y} yellow", "ui.p_chars": "{n} characters scanned", "ui.why_fail": "Why it fails people",
        "ui.p_clean": "None of the known failure rules matched. That is not a clean bill — read the drawdown section yourself.",
        "ui.p_saved": "Saved comparisons", "ui.paid": "Paid", "ui.size": "Size", "ui.pass": "Pass", "ui.breakeven": "Breakeven",
        "ui.p_nosave": "Nothing saved yet. Use <em>Calculate & save</em> to line firms up side by side. Comparisons live in this browser session.",
        "ui.i_model": "Revenue model", "ui.i_broker": "Broker", "ui.i_lots": "Lots per client / month", "ui.i_rate": "Rebate $ per lot", "ui.i_clients": "Active clients",
        "ui.i_claw": "Clawback %", "ui.i_comp": "Compliance cost $ / month", "ui.i_thresh": "Payout threshold $", "ui.i_hold": "Hold period (days)",
        "ui.i_net": "Net per month", "ui.i_net_note": "{annual} a year · {margin} margin", "ui.i_gross": "Gross rebate", "ui.i_gross_note": "−{claw} clawback · −{comp} compliance",
        "ui.i_first": "First cash lands", "ui.i_day": "day {d}", "ui.i_first_note": "{thresh} threshold + {days}-day hold",
        "ui.i_timeline": "Payout timeline", "ui.earned": "Earned", "ui.paid_out": "Paid out", "ui.held": "Held back", "ui.cumulative": "Cumulative paid",
        "ui.i_share": "Shareable link to this exact model: the address bar. The payout threshold and hold period are the two numbers to confirm in writing before you refer a single client.",
        "ui.i_checklist": "Compliance checklist", "ui.i_download": "⬇ Download the checklist (.txt)", "ui.i_saved": "Saved scenarios",
        "ui.rate": "Rate", "ui.clients": "Clients", "ui.net_month": "Net / month", "ui.annual": "Annual", "ui.first_cash": "First cash",
        "ui.i_nosave": "Nothing saved yet. Use <em>Calculate & save</em> to line brokers up side by side. Scenarios live in this browser session.",
        "ui.c_baseline": "Baseline spread", "ui.c_season": "Seasonality · 12 months", "ui.c_season_note": "{src} · average monthly return; bar height is the size of the move.",
        "ui.c_hist": "What the spread did last time", "ui.measured": "Measured", "ui.worst": "Worst spread", "ui.mean": "Mean", "ui.vs_base": "vs baseline",
        "ui.s_h_bot": "Audit a bot", "ui.s_h_copy": "Audit a copy-trade broker", "ui.s_h_scan": "Scan a signal pitch", "ui.s_h_inf": "Audit an influencer",
        "ui.audit": "Audit", "ui.scan": "Scan",
        "ui.s_ph_bot": "Paste the bot's welcome message, the link it sent, or the DM…", "ui.s_ph_copy": "Paste the pitch: 'copy my trades, 10% a month, sign up with my link…'",
        "ui.s_ph_scan": "Paste the whole pitch — the channel post, the DM, the sales page…", "ui.s_ph_inf": "Paste their post, bio, pinned message or DM, links included…",
        "ui.s_sub_bot": "Bot username", "ui.s_txt_bot": "Paste what the bot said (optional)", "ui.s_sub_copy": "Broker", "ui.s_txt_copy": "Paste the copy-trade pitch (optional)",
        "ui.s_sub_scan": "Channel or seller (optional)", "ui.s_txt_scan": "Paste the pitch", "ui.s_sub_inf": "Influencer handle", "ui.s_txt_inf": "Paste their post, bio or DM (optional)",
        "ui.s_spread": "Typical spread (pips)", "ui.s_lots": "Lots you copy per month", "ui.s_need_sub": "{label} is required.", "ui.s_need_text": "Paste the pitch first.",
        "ui.s_flags": "Flags", "ui.s_rgy": "red / yellow / good", "ui.s_reg": "Regulation", "ui.s_tier1": "Tier-1", "ui.s_offshore": "Offshore only", "ui.s_unknown": "Unknown",
        "ui.s_not_table": "not in our table", "ui.s_cost_year": "Spread cost / year", "ui.s_cost_note": "${m:,.0f} a month at {p:g} pips × {l:g} lots",
        "ui.s_ref": "Broker referral links", "ui.s_ref_note": "they get paid when you deposit", "ui.s_share": "Share link", "ui.s_community": "scanned {n}× by the community",
        "ui.s_checklist": "Checklist", "ui.s_verify": "Verify on the register", "ui.regulator": "Regulator", "ui.meaning": "What it means", "ui.register": "Register", "ui.open": "open ↗",
        "ui.s_trail": "Broker-promotion trail", "ui.s_watch": "Watchlist", "ui.scans": "Scans", "ui.latest": "Latest score", "ui.rescan": "Re-scan",
        "ui.s_run": "Run your own scan", "ui.s_scan_n": "scan #{n}",
        "ui.l_title": "Loss-report template", "ui.l_lede": "Lost money already? Fill this in and download the report in the shape the FTC, CFTC, IC3, SC Malaysia and BNM forms ask for.",
        "ui.l_handle": "Influencer handle", "ui.l_platform": "Platform", "ui.l_broker": "Broker / venue promoted", "ui.l_amount": "Amount lost", "ui.l_currency": "Currency",
        "ui.l_date": "Date(s)", "ui.l_story": "What happened, in order", "ui.l_story_ph": "First contact, what was promised, what you paid, what happened after…",
        "ui.l_download": "⬇ Download report.txt",
        "scan.score": "score", "scan.subject": "Subject",
        "scan.verdict_high": "HIGH RISK", "scan.verdict_caution": "CAUTION", "scan.verdict_low": "LOW RISK",
        "scan.more": "… {n} more findings on the dashboard.", "scan.clean": "No flags found in this text. That is not proof it is safe.",
        "scan.saved": "Saved as scan #{n} — history and watchlist are on the dashboard.",
        "scan.disclaimer": "Education only. Not financial advice.",
        "scan.usage_audit": "Usage: <code>/audit @bot_username [what the bot said]</code>\nExample: <code>/audit @wallet_verify_b0t send your seed phrase to claim</code>",
        "scan.usage_copy": "Usage: <code>/copyaudit BROKER [SPREAD_PIPS] [LOTS_PER_MONTH]</code>\nExample: <code>/copyaudit exness 2 10</code>",
        "scan.usage_scan": "Usage: <code>/scan TEXT</code> — paste the signal pitch (at least one sentence).",
        "scan.usage_influencer": "Usage: <code>/influencer @handle [their post or DM]</code>",
        "scan.tail_audit": "Check: name ends in 'bot', linked from the official site, never asks for a seed phrase or a fee.",
        "scan.tail_copy": "Verify the licence number on the regulator's register before you deposit.",
        "scan.tail_scan": "Ask for a verified Myfxbook / FX Blue account. Screenshots are not proof.",
        "scan.regs": "Regulators in our table: {regs}",
        "scan.cost": "Spread cost: {pips:g} pips × {lots:g} lots ≈ <b>${monthly:,.0f}/month</b> · ${yearly:,.0f}/year",
        "scan.demand": "Demand from them:",
        "scan.ib_links": "🔗 {n} broker referral link(s) found — they get paid when you deposit.",
    },
}


def t(key, lang=DEFAULT_LANG, **kwargs):
    """Look a string up in `lang`, falling back to Bahasa Melayu, then to the key."""
    table = STRINGS.get(lang) or STRINGS[DEFAULT_LANG]
    text = table.get(key) or STRINGS[DEFAULT_LANG].get(key) or key
    return text.format(brand=BRAND["name"], since=BRAND["since"], **kwargs) if ("{" in text) else text


def rank_label(rank, lang=DEFAULT_LANG):
    return RANKS.get(rank, RANKS["public"]).get(lang) or RANKS["public"]["ms"]


def normalise_lang(code):
    """Telegram language codes → our two. Indonesian reads Malay comfortably."""
    code = (code or "").lower()
    if code.startswith(("ms", "id")):
        return "ms"
    if code.startswith("en"):
        return "en"
    return None
