"""SAMBANGGOLD brand: one place for the name, the tokens and every user-facing string.

Mirrors ``src/config/brand.ts`` and ``messages/{ms,en}.json`` in the website repo
so the dashboard, the bot and the site read as one product. Bahasa Melayu is the
default; English is the second language. Product names, rank names and brand
names stay untranslated — only the surrounding words change.
"""

BRAND = {
    "name": "SAMBANGGOLD",
    "short": "SBG",
    "person": "Sam",
    "since": 2022,
    "tagline": {"ms": "Alat emas, telus.", "en": "Gold tools, transparent."},
    "group": "Sam Flip Seribu",
}

# Sam's palette, verbatim from the website's globals.css.
TOKENS = {
    "bg": "#050505", "surface": "#0b0e14", "surface2": "#11151d", "border": "#1e2330",
    "fg": "#f3f4f6", "muted": "#9aa3b2", "gold": "#d4af37", "gold2": "#f5d76e",
    "gold_deep": "#7a4003", "win": "#00c46a", "loss": "#ff4d4f", "chrome": "#b7c0ce",
    "graphite": "#050609",
}

# Rank vocabulary from the website: Awam (public) → General (free) → A-Team → Rambo.
RANKS = {
    "public": {"ms": "Awam", "en": "Public"},
    "free": {"ms": "General", "en": "General"},
    "pro": {"ms": "A-Team", "en": "A-Team"},
    "elite": {"ms": "Rambo", "en": "Rambo"},
}

LANGS = ("ms", "en")
DEFAULT_LANG = "ms"

STRINGS = {
    "ms": {
        # nav
        "nav.products": "Produk", "nav.dashboard": "Dashboard", "nav.account": "Akaun",
        "nav.signin": "Log masuk", "nav.signout": "Log keluar", "nav.admin": "Admin",
        "nav.cta": "Buka bot", "nav.lang": "EN",
        # landing
        "hero.badge": "Sejak {since} · SAMBANGGOLD · 18 alat emas",
        "hero.title": "Alat emas, telus.", "hero.title2": "Dua permukaan.",
        "hero.subtitle": "Setiap alat menjawab di Telegram dan mempunyai halaman sendiri di sini. Satu akaun Telegram menyambungkan kedua-duanya. Semua ada tier percuma, tiada yang dikunci di pintu.",
        "hero.cta_primary": "Buka bot Telegram", "hero.cta_secondary": "Lihat semua alat",
        "hero.note": "Pendidikan sahaja. Bukan nasihat kewangan.",
        "stats.products": "Alat", "stats.live": "Sudah hidup", "stats.free": "Tier percuma", "stats.since": "Sejak",
        "doors.title": "Dua cara guna", "doors.subtitle": "Sama alat, sama tier percuma. Pilih di mana anda mahu jawapan itu sampai.",
        "doors.a_title": "🤖 Di Telegram", "doors.a_body": "Satu arahan, satu jawapan. Alert masuk terus ke chat anda.", "doors.a_cta": "Buka bot",
        "doors.b_title": "🌐 Di dashboard", "doors.b_body": "Sejarah, tetapan, eksport CSV. Semua yang chat tak boleh simpan.", "doors.b_cta": "Log masuk",
        "grid.title": "Lapan belas alat", "grid.subtitle": "{live} sudah hidup. {queued} lagi dalam giliran — spesifikasi ditulis, halaman ditempah.",
        "grid.live": "Hidup", "grid.queued": "Giliran", "grid.open": "Buka",
        "faq.title": "Soalan lazim",
        "faq.q1": "Perlu bayar ke?", "faq.a1": "Tidak. Setiap alat ada tier percuma yang berfungsi sepenuhnya. Tier berbayar jual skala dan automasi sahaja.",
        "faq.q2": "Kenapa perlu akaun Telegram?", "faq.a2": "Supaya alert dari bot dan sejarah di dashboard adalah satu senarai. Boleh juga daftar dengan emel dan pautkan Telegram kemudian.",
        "faq.q3": "Data harga dari mana?", "faq.a3": "Binance PAXGUSDT (bid dan ask sebenar) dengan Yahoo Finance GC=F sebagai sandaran. Kedua-duanya percuma dan awam.",
        "faq.q4": "Ini nasihat kewangan?", "faq.a4": "Bukan. Semua ini untuk pendidikan. Sahkan setiap harga dengan broker anda sendiri.",
        # sign-in
        "signin.title": "Log masuk", "signin.subtitle": "Telegram, emel, atau Google. Tiada kata laluan.",
        "signin.telegram": "Log masuk dengan Telegram", "signin.telegram_hint": "Butang ini ingat akaun Telegram terakhir. Untuk tukar: app Telegram → Tetapan → Privasi & Keselamatan → Laman web → putuskan sambungan.",
        "signin.email_label": "Emel anda", "signin.email_cta": "Hantar kod 8 digit",
        "signin.email_hint": "Kami hantar kod 8 digit ke emel anda. Sah selama 10 minit.",
        "signin.google": "Teruskan dengan Google", "signin.google_soon": "Akan datang",
        "signin.or": "atau",
        "verify.title": "Semak emel anda", "verify.subtitle": "Kod 8 digit dihantar ke {email}.",
        "verify.code_label": "Kod", "verify.cta": "Sahkan & masuk", "verify.resend": "Hantar semula",
        "verify.wrong": "Kod salah atau sudah tamat. Cuba lagi.", "verify.too_many": "Terlalu banyak cubaan. Minta kod baharu.",
        "verify.cooldown": "Tunggu seminit sebelum minta kod baharu.", "verify.bad_email": "Emel tidak sah.",
        "verify.mail_down": "Emel tidak dapat dihantar buat masa ini. Guna Telegram, atau cuba sebentar lagi.",
        "verify.sent": "Kod dihantar.", "verify.dev_code": "Mod dev — kod anda: {code}",
        "google.title": "Google — akan datang", "google.body": "Log masuk Google sedang disediakan. Guna Telegram atau emel buat masa ini.",
        # dashboard
        "dash.title": "Dashboard ahli", "dash.subtitle": "Alat anda, alert anda, rekod anda.",
        "dash.rank": "Pangkat semasa", "dash.member_since": "Ahli sejak", "dash.upgrade": "Naik ke A-Team untuk automasi",
        "dash.alerts": "Alert aktif", "dash.triggers": "Alert dicetus", "dash.saved": "Perbandingan disimpan", "dash.linked": "Telegram dipautkan",
        "dash.live": "Alat hidup", "dash.queued": "Dalam giliran", "dash.open": "Buka alat",
        "dash.link_tg": "Pautkan Telegram supaya alert masuk ke chat anda.", "dash.link_email": "Tambah emel supaya anda boleh log masuk tanpa Telegram.",
        "dash.not_linked": "Belum dipautkan",
        # account
        "account.title": "Akaun", "account.email": "Emel", "account.telegram": "Telegram", "account.lang": "Bahasa",
        "account.none": "Tiada", "account.signout": "Log keluar", "account.admin": "Anda admin. Semua ciri terbuka.",
        # admin
        "admin.title": "Admin", "admin.subtitle": "Setiap akaun, emel dan pautan Telegram.",
        "admin.users": "Akaun", "admin.emails": "Dengan emel", "admin.telegrams": "Dengan Telegram", "admin.starts": "Bot /start",
        "admin.export": "Eksport CSV", "admin.col_email": "Emel", "admin.col_tg": "Telegram", "admin.col_name": "Nama",
        "admin.col_lang": "Bahasa", "admin.col_created": "Daftar", "admin.col_last": "Log masuk akhir",
        # product page
        "product.bot_half": "Separuh Telegram", "product.web_half": "Separuh dashboard", "product.free": "Tier percuma",
        "product.live_note": "Hidup di bawah — nombor yang sama bot berikan.",
        "product.soon": "Panel akan hidup apabila setiap paparan disambung ke data.",
        "product.queued": "Dalam giliran — spesifikasi ditulis, permukaan ditempah.",
        "product.upsell": "Naik taraf", "product.upsell_note": "Tier berbayar jual skala dan automasi sahaja, bukan akses asas.",
        "product.back": "Semua alat", "product.signin": "Log masuk untuk simpan dan eksport.",
        # footer
        "footer.legal": "Undang-undang", "footer.risk": "Pendedahan risiko", "footer.rights": "Untuk pendidikan sahaja. Bukan nasihat kewangan.",
        "risk.strip": "Dagangan emas, forex dan CFD secara margin melibatkan risiko yang tinggi dan anda boleh kehilangan lebih daripada deposit awal. Prestasi lepas bukan petunjuk prestasi akan datang. Semua kandungan adalah untuk tujuan pendidikan sahaja dan bukan nasihat kewangan. Sahkan setiap harga dengan broker anda.",
        # email
        "mail.subject": "Kod log masuk {brand} anda: {code}",
        "mail.body": "Kod log masuk anda: {code}\n\nSah selama 10 minit. Jika anda tidak minta kod ini, abaikan emel ini.\n\n{brand} · Pendidikan sahaja. Bukan nasihat kewangan.",
        # bot
        "bot.pick_lang": "🌐 Pilih bahasa / Choose your language:",
        "bot.lang_set": "Bahasa ditukar ke Bahasa Melayu.",
        "bot.welcome": "<b>{brand}</b>. 18 alat emas, setiap satu menjawab di sini dan di dashboard.\n\nSemua ada tier percuma. Tiada yang dikunci di pintu.\n\n⚠️ Dagangan CFD berisiko tinggi. Pendidikan sahaja, bukan nasihat kewangan.",
        "bot.menu": "Apa yang anda mahu buat?",
        "bot.btn_tools": "🥇 Cuba alat percuma", "bot.btn_dash": "🌐 Buka dashboard", "bot.btn_faq": "❓ Soalan lazim",
        "bot.btn_channel": "📢 Channel awam", "bot.btn_back": "⬅️ Kembali", "bot.btn_menu": "⬅️ Menu Utama",
        "bot.btn_try": "▶️ Cuba contoh", "bot.btn_open": "🌐 Buka di dashboard", "bot.btn_share": "📤 Kongsi", "bot.btn_again": "🔁 Cuba lagi",
        "bot.btn_more": "🔮 Lihat yang dalam giliran",
        "bot.tools": "<b>Alat yang sudah hidup</b>\nPilih satu. Setiap satu percuma.",
        "bot.queued": "<b>Dalam giliran</b>\nSpesifikasi ditulis, halaman ditempah. Bot akan jawab bila hidup.",
        "bot.tool_card": "{emoji} <b>{name}</b>\n{solution}\n\n<b>Tier percuma:</b> {free}\n<b>Arahan:</b> <code>{command}</code>",
        "bot.faq": "<b>Soalan lazim</b>\n\n<b>Perlu bayar ke?</b> Tidak. Setiap alat ada tier percuma yang berfungsi sepenuhnya.\n\n<b>Kenapa Telegram?</b> Supaya alert di sini dan sejarah di dashboard adalah satu senarai.\n\n<b>Data harga?</b> Binance PAXGUSDT, sandaran Yahoo GC=F. Percuma dan awam.\n\n<b>Nasihat kewangan?</b> Bukan. Pendidikan sahaja.",
        "bot.help": "<b>Arahan</b>", "bot.help_tail": "/start — menu · /language — tukar bahasa · /dashboard — pautan dashboard\n\nPendidikan sahaja. Bukan nasihat kewangan.",
        "bot.dash": "Dashboard anda. Log masuk dengan Telegram — akaun yang sama, senarai alert yang sama.",
        "bot.unknown": "Arahan tak dikenali. Hantar /start untuk menu.",
        "bot.queued_reply": "{emoji} <b>{name}</b> — dalam giliran.\n{solution}",
        "bot.result_tail": "Simpan, eksport dan bandingkan di dashboard.",
        "bot.share_text": "Saya guna {brand} untuk emas. Cuba percuma:",
        # calendar
        "cal.title": "📅 <b>Kalendar emas</b>",
        "cal.next": "Acara USD merah seterusnya", "cal.none": "Tiada acara merah dalam suapan minggu ini.",
        "cal.fomc": "FOMC seterusnya", "cal.holiday": "Cuti CME seterusnya", "cal.season": "Bulan ini (purata {n} tahun)",
        "cal.season_line": "pulangan {ret:+.1f}% · julat {rng:.1f}%",
        "cal.on": "🔔 Alert 30 minit sebelum: <b>HIDUP</b>", "cal.off": "🔕 Alert 30 minit sebelum: <b>MATI</b>",
        "cal.btn_on": "🔔 Hidupkan alert", "cal.btn_off": "🔕 Matikan alert",
        "cal.push": "⏰ <b>{title}</b> dalam 30 minit ({when} MYT).\nSpread biasanya melebar. Pendidikan sahaja.",
        "cal.need_chat": "Alert perlukan chat Telegram. Buka bot dan hantar /calendar_alert.",
        "cal.spread_note": "Spread diukur setiap 5 minit; sejarah setiap acara terkumpul dari sini.",

        # sign-in extras
        "signin.no_username": "Butang Telegram akan muncul sebaik TELEGRAM_BOT_USERNAME ditetapkan pada pelayan.",
        # #1 bot replies
        "watch.usage": "Guna:\n<code>/watch XAUUSD</code> — harga langsung, spread dan paras entry/stop\n<code>/watch XAUUSD above 2450</code> — alert bila <i>ask</i> sampai 2450\n<code>/watch XAUUSD below 2380</code> — alert bila <i>bid</i> jatuh ke 2380\n<code>/watch list</code> · <code>/watch clear</code>\n\nAtau tekan ▶️ Mula dan bot akan tanya satu-satu.",
        "watch.none": "Tiada alert dipasang.", "watch.list": "<b>Alert dipasang</b>", "watch.cleared": "{n} alert dibuang.",
        "watch.only_gold": "Emas sahaja buat masa ini (<code>XAUUSD</code>). Berbilang pasangan ada di tier PRO.",
        "watch.feed_down": "Suapan harga tak tersedia sekarang ({err}). Cuba lagi seminit.",
        "watch.armed": "Dipasang: ", "watch.level_num": "Paras mesti nombor.", "watch.need_chat": "Alert perlukan chat Telegram untuk dihantar.",
        "watch.ok": "✅ Alert #{id} dipasang: {sym} {dir} {level} (cetus pada {side}).\nSekarang: bid {bid} · ask {ask}",
        "watch.spread": "Spread {spread} · {src}", "watch.nobook": "n/a (tiada order book)",
        "watch.long": "Long: masuk {e}, stop {s}", "watch.short": "Short: masuk {e}, stop {s}",
        "watch.above": "naik melepasi", "watch.below": "turun bawah",
        "watch.d_armed": "Alert #{id} dipasang.", "watch.d_updated": "Paras dikemas kini.", "watch.d_disarmed": "Alert dibuang.",
        "watch.fire": "🔔 <b>XAUUSD {dir} {level}</b> — {side} sekarang {price} ({src})\nPendidikan sahaja. Sahkan dengan broker anda.",
        # #3 #8 bot replies
        "prop.usage": "Guna: <code>/propcalc YURAN SAIZ LULUS%</code>\nContoh: <code>/propcalc 500 100000 15</code> — yuran $500 pada akaun $100k dengan 15% peluang lulus.\n\nAtau tekan ▶️ Mula dan bot akan tanya satu-satu.",
        "prop.reply": "{tone} <b>EV {ev}</b> atas yuran {cost} ({roi} ROI)\nPayout pertama jika funded: {payout} (sasaran {target} × pembahagian {split} pada {size})\nKadar lulus pulang modal: <b>{be}</b> — anda kata {pass}\n\nTampal terma firm di dashboard untuk imbasan peraturan.",
        "ib.usage": "Guna: <code>/ibcalc LOT KADAR [KLIEN] [CLAWBACK%]</code>\nContoh: <code>/ibcalc 40 7 25 5</code> — 25 klien trade 40 lot sebulan pada $7 setiap lot dengan 5% clawback.\n\nAtau tekan ▶️ Mula dan bot akan tanya satu-satu.",
        "ib.reply": "<b>{net} bersih sebulan</b> · {annual} setahun\nKasar {gross} dari {clients} klien × {lots:g} lot × ${rate:g}\nClawback {claw} · margin {margin}\n\nTambah kos pematuhan, ambang payout dan tempoh pegangan di dashboard untuk lihat bila tunai pertama masuk.",
        # guided flows
        "flow.start": "▶️ Mula", "flow.example": "💡 Contoh", "flow.cancel": "✖ Batal", "flow.skip": "⏭ Langkau",
        "flow.cancelled": "Dibatalkan. Hantar /start untuk menu.", "flow.not_number": "Nombor sahaja, contoh <code>2450</code>. Cuba lagi.",
        "flow.chosen": "{prompt}\n\n✅ {value}", "flow.typed": "Atau taip nilai anda sendiri.",
        "flow.watch_mode": "🥇 <b>Gold Watch</b>\nApa yang anda mahu?",
        "flow.watch_price": "📈 Harga sekarang", "flow.watch_above": "🔔 Alert bila naik melepasi…", "flow.watch_below": "🔔 Alert bila turun bawah…",
        "flow.watch_level": "Masukkan paras harga (contoh <code>2450</code>).",
        "flow.prop_fee": "🏛 <b>Prop Firm Challenge</b>\nYuran challenge (USD)?",
        "flow.prop_size": "Saiz akaun (USD)?", "flow.prop_pass": "Peluang anda lulus (%)? Industri: 10–25%.",
        "flow.ib_lots": "🥇 <b>IB Revenue</b>\nLot setiap klien sebulan?", "flow.ib_rate": "Rebate (USD) setiap lot?",
        "flow.ib_clients": "Berapa klien aktif?", "flow.ib_claw": "Clawback (%)?",
        "flow.audit_handle": "🔒 <b>Bot Scam Detector</b>\nHantar username bot itu (contoh <code>@wallet_verify_b0t</code>).",
        "flow.audit_text": "Tampal apa yang bot itu kata — atau Langkau.",
        "flow.copy_broker": "🔒 <b>Copy-Trade Audit</b>\nBroker mana? Pilih atau taip nama.",
        "flow.copy_spread": "Spread biasa (pip)? Atau Langkau.", "flow.copy_lots": "Lot yang anda copy sebulan? Atau Langkau.",
        "flow.scan_text": "💱 <b>Red-Flag Scanner</b>\nTampal pitch signal itu di sini — post channel, DM, atau halaman jualan.",
        "flow.inf_handle": "🔒 <b>Influencer Audit</b>\nHandle influencer itu (contoh <code>@gold_guru</code>)?",
        "flow.inf_text": "Tampal post, bio atau DM mereka, termasuk pautan — atau Langkau.",
        # dashboard tool panels
        "ui.calc": "Kira", "ui.calc_save": "Kira & simpan", "ui.verdict": "Verdict", "ui.rule": "Peraturan", "ui.where": "Di mana",
        "ui.why": "Kenapa penting", "ui.flag": "Bendera", "ui.history": "Sejarah", "ui.when": "Bila (UTC)", "ui.source": "Sumber",
        "ui.price": "Harga", "ui.never": "tak pernah", "ui.month": "Bulan", "ui.event": "Acara", "ui.forecast": "Ramalan", "ui.previous": "Sebelum",
        "ui.w_live": "Emas langsung", "ui.w_mid": "XAUUSD tengah", "ui.w_bidask": "Bid / ask", "ui.w_bidask_note": "harga sebenar yang anda dapat",
        "ui.w_nobook": "tiada order book pada sumber ini", "ui.w_peroz": "seauns", "ui.w_stopnote": "Stop 0.5% dilebarkan mengikut spread — titik mula, bukan signal.",
        "ui.w_feed_err": "Suapan tak tersedia: {err}", "ui.w_armed": "Alert dipasang",
        "ui.w_signin": "Log masuk dengan Telegram (atas kanan) untuk lihat alert yang anda pasang di bot, ubah paras dan eksport sejarah. Satu akaun, dua permukaan.",
        "ui.w_dir": "Arah", "ui.w_above": "naik melepasi — cetus pada ask", "ui.w_below": "turun bawah — cetus pada bid", "ui.w_level": "Paras",
        "ui.w_arm": "Pasang alert", "ui.w_pair": "Pasangan", "ui.w_save": "Simpan", "ui.w_disarm": "Buang",
        "ui.w_none": "Tiada alert. Pasang di sini atau hantar <code>/watch XAUUSD above 2450</code> ke bot — senarai yang sama.",
        "ui.w_hist": "Sejarah alert", "ui.w_fired": "Dicetus (UTC)", "ui.w_alert": "Alert", "ui.w_export": "⬇ Eksport sejarah (.csv)",
        "ui.w_nohist": "Belum ada cetusan. Setiap satu direkod dengan harga dan spread ketika itu — jurnal yang chat tak boleh beri.",
        "ui.p_calc": "Kalkulator", "ui.p_firm": "Firm", "ui.p_fee": "Yuran challenge $", "ui.p_size": "Saiz akaun $", "ui.p_pass": "Peluang lulus anda %",
        "ui.p_target": "Sasaran untung %", "ui.p_split": "Pembahagian untung %", "ui.p_resets": "Reset dibeli", "ui.optional": "pilihan",
        "ui.p_ev": "Expected value", "ui.p_on_paid": "{roi} atas {cost} dibayar", "ui.p_breakeven": "Kadar lulus pulang modal", "ui.p_entered": "anda masukkan {p}",
        "ui.p_first": "Payout pertama jika funded", "ui.p_target_split": "sasaran {target} × pembahagian {split}",
        "ui.p_share": "Pautan kongsi untuk keputusan ini ialah bar alamat. Kadar lulus industri sekitar 10–25%; jika pulang modal anda di atas julat itu, yuran itu tak berpihak kepada anda.",
        "ui.p_scan": "Imbasan peraturan", "ui.p_paste": "Tampal terma challenge", "ui.p_paste_ph": "Tampal halaman peraturan atau T&C firm di sini…", "ui.p_scan_btn": "Imbas terma",
        "ui.p_reds": "{r} merah · {y} kuning", "ui.p_chars": "{n} aksara diimbas", "ui.why_fail": "Kenapa ia gagalkan orang",
        "ui.p_clean": "Tiada peraturan gagal yang dikenali sepadan. Itu bukan bil bersih — baca bahagian drawdown sendiri.",
        "ui.p_saved": "Perbandingan disimpan", "ui.paid": "Dibayar", "ui.size": "Saiz", "ui.pass": "Lulus", "ui.breakeven": "Pulang modal",
        "ui.p_nosave": "Belum ada yang disimpan. Guna <em>Kira & simpan</em> untuk banding firm sebelah-menyebelah. Perbandingan kekal dalam sesi pelayar ini.",
        "ui.i_model": "Model hasil", "ui.i_broker": "Broker", "ui.i_lots": "Lot setiap klien / bulan", "ui.i_rate": "Rebate $ setiap lot", "ui.i_clients": "Klien aktif",
        "ui.i_claw": "Clawback %", "ui.i_comp": "Kos pematuhan $ / bulan", "ui.i_thresh": "Ambang payout $", "ui.i_hold": "Tempoh pegangan (hari)",
        "ui.i_net": "Bersih sebulan", "ui.i_net_note": "{annual} setahun · margin {margin}", "ui.i_gross": "Rebate kasar", "ui.i_gross_note": "−{claw} clawback · −{comp} pematuhan",
        "ui.i_first": "Tunai pertama masuk", "ui.i_day": "hari {d}", "ui.i_first_note": "ambang {thresh} + pegangan {days} hari",
        "ui.i_timeline": "Garis masa payout", "ui.earned": "Diperoleh", "ui.paid_out": "Dibayar", "ui.held": "Ditahan", "ui.cumulative": "Kumulatif dibayar",
        "ui.i_share": "Pautan kongsi untuk model ini: bar alamat. Ambang payout dan tempoh pegangan ialah dua nombor yang perlu disahkan secara bertulis sebelum anda rujuk seorang klien pun.",
        "ui.i_checklist": "Senarai semak pematuhan", "ui.i_download": "⬇ Muat turun senarai semak (.txt)", "ui.i_saved": "Senario disimpan",
        "ui.rate": "Kadar", "ui.clients": "Klien", "ui.net_month": "Bersih / bulan", "ui.annual": "Setahun", "ui.first_cash": "Tunai pertama",
        "ui.i_nosave": "Belum ada yang disimpan. Guna <em>Kira & simpan</em> untuk banding broker sebelah-menyebelah. Senario kekal dalam sesi pelayar ini.",
        "ui.c_baseline": "Spread asas", "ui.c_season": "Musim · 12 bulan", "ui.c_season_note": "{src} · purata pulangan bulanan; tinggi bar ialah saiz pergerakan.",
        "ui.c_hist": "Apa spread buat kali lepas", "ui.measured": "Diukur", "ui.worst": "Spread terburuk", "ui.mean": "Purata", "ui.vs_base": "vs asas",
        "ui.s_h_bot": "Audit bot", "ui.s_h_copy": "Audit broker copy-trade", "ui.s_h_scan": "Imbas pitch signal", "ui.s_h_inf": "Audit influencer",
        "ui.audit": "Audit", "ui.scan": "Imbas",
        "ui.s_ph_bot": "Tampal mesej alu-aluan bot itu, pautan yang ia hantar, atau DM…", "ui.s_ph_copy": "Tampal pitch: 'copy trade saya, 10% sebulan, daftar guna link saya…'",
        "ui.s_ph_scan": "Tampal seluruh pitch — post channel, DM, halaman jualan…", "ui.s_ph_inf": "Tampal post, bio, mesej pin atau DM mereka, termasuk pautan…",
        "ui.s_sub_bot": "Username bot", "ui.s_txt_bot": "Tampal apa yang bot itu kata (pilihan)", "ui.s_sub_copy": "Broker", "ui.s_txt_copy": "Tampal pitch copy-trade (pilihan)",
        "ui.s_sub_scan": "Channel atau penjual (pilihan)", "ui.s_txt_scan": "Tampal pitch", "ui.s_sub_inf": "Handle influencer", "ui.s_txt_inf": "Tampal post, bio atau DM mereka (pilihan)",
        "ui.s_spread": "Spread biasa (pip)", "ui.s_lots": "Lot yang anda copy sebulan", "ui.s_need_sub": "{label} diperlukan.", "ui.s_need_text": "Tampal pitch dahulu.",
        "ui.s_flags": "Bendera", "ui.s_rgy": "merah / kuning / baik", "ui.s_reg": "Lesen", "ui.s_tier1": "Tier-1", "ui.s_offshore": "Offshore sahaja", "ui.s_unknown": "Tak dikenali",
        "ui.s_not_table": "tiada dalam jadual kami", "ui.s_cost_year": "Kos spread / tahun", "ui.s_cost_note": "${m:,.0f} sebulan pada {p:g} pip × {l:g} lot",
        "ui.s_ref": "Pautan rujukan broker", "ui.s_ref_note": "mereka dibayar bila anda deposit", "ui.s_share": "Pautan kongsi", "ui.s_community": "diimbas {n}× oleh komuniti",
        "ui.s_checklist": "Senarai semak", "ui.s_verify": "Sahkan di daftar", "ui.regulator": "Regulator", "ui.meaning": "Maksudnya", "ui.register": "Daftar", "ui.open": "buka ↗",
        "ui.s_trail": "Jejak promosi broker", "ui.s_watch": "Senarai pantau", "ui.scans": "Imbasan", "ui.latest": "Skor terkini", "ui.rescan": "Imbas semula",
        "ui.s_run": "Buat imbasan anda sendiri", "ui.s_scan_n": "imbasan #{n}",
        "ui.l_title": "Templat laporan kerugian", "ui.l_lede": "Sudah rugi? Isi dan muat turun laporan dalam bentuk yang borang FTC, CFTC, IC3, SC Malaysia dan BNM minta.",
        "ui.l_handle": "Handle influencer", "ui.l_platform": "Platform", "ui.l_broker": "Broker / platform yang dipromosi", "ui.l_amount": "Jumlah rugi", "ui.l_currency": "Mata wang",
        "ui.l_date": "Tarikh", "ui.l_story": "Apa yang berlaku, mengikut urutan", "ui.l_story_ph": "Hubungan pertama, apa yang dijanjikan, apa yang anda bayar, apa jadi selepas itu…",
        "ui.l_download": "⬇ Muat turun report.txt",
        # #2 verifier
        "ver.usage": "Guna: <code>/verify GOLD HARGA [TARIKH] [MASA]</code>\nContoh: <code>/verify GOLD 2431.5 2026-09-14 14:30</code> (MYT). Tanpa tarikh = 24 jam lepas.\n\nAtau tekan ▶️ Mula dan bot akan tanya satu-satu.",
        "ver.bad_input": "Harga mesti nombor; tarikh YYYY-MM-DD; masa HH:MM (MYT).",
        "ver.v_real": "REAL", "ver.v_borderline": "BORDERLINE", "ver.v_impossible": "IMPOSSIBLE", "ver.v_unverified": "TAK DAPAT SAHKAN",
        "ver.line_range": "Julat tetingkap: {low} – {high} ({src}, {n} candle 1 minit)",
        "ver.line_nearest": "Candle terdekat: {at} MYT · low {low} · high {high}",
        "ver.line_gap": "Di luar julat sebanyak ${gap} ({pct:.2f}%).",
        "ver.line_nodata": "Tiada candle untuk tetingkap ini. {err}",
        "ver.note": "PAXG ialah emas satu auns di Binance; broker anda mungkin beza beberapa dolar. BORDERLINE = dalam had toleransi itu. Minta penyata akaun, bukan screenshot.",
        "flow.ver_price": "🥇 <b>Signal Verifier</b>\nHarga fill yang didakwa? (contoh <code>2431.5</code>)",
        "flow.ver_date": "Tarikh fill itu (YYYY-MM-DD, MYT)? Langkau = 24 jam lepas.",
        "flow.ver_time": "Masa (HH:MM, MYT)? Langkau = sepanjang hari itu.",
        "ui.v_h": "Semak satu fill", "ui.v_price": "Harga didakwa", "ui.v_date": "Tarikh (MYT)", "ui.v_time": "Masa (MYT)", "ui.v_side": "Arah",
        "ui.v_any": "mana-mana", "ui.v_buy": "buy", "ui.v_sell": "sell", "ui.v_btn": "Semak",
        "ui.v_batch": "Semak beramai-ramai", "ui.v_batch_label": "Satu dakwaan setiap baris: HARGA [TARIKH] [MASA] [buy|sell]",
        "ui.v_batch_ph": "2431.5 2026-09-14 14:30 buy\n2418.0 2026-09-14\n2455.2",
        "ui.v_batch_btn": "Semak semua", "ui.v_need_lines": "Tampal sekurang-kurangnya satu baris.",
        "ui.v_window": "Tetingkap", "ui.v_range": "Julat", "ui.v_candles": "candle", "ui.v_gap": "Jarak", "ui.v_claim": "Dakwaan",
        "ui.v_nohist": "Belum ada semakan. Setiap verdict disimpan di sini dengan tetingkap candle yang menghasilkannya.",
        "ui.v_lede": "Tampal harga dari screenshot signal itu. Kami semak sama ada harga itu pernah dicetak dalam candle 1 minit Binance PAXGUSDT. Tarikh dan masa dalam MYT.",
        # #10 rebate
        "reb.usage": "Guna: <code>/rebateaudit</code> — ringkasan larian terakhir anda di dashboard.\nAtau kira pantas: <code>/rebateaudit LOT KADAR DIBAYAR</code>, contoh <code>/rebateaudit 42.5 8 300</code>.",
        "reb.quick": "{lots:g} lot × ${rate:g} = <b>${expected:,.2f}</b> dijangka · dibayar ${paid:,.2f} · {label} <b>${diff:,.2f}</b>",
        "reb.short": "kekurangan", "reb.over": "lebihan", "reb.exact": "tepat",
        "reb.none": "Belum ada larian. Muat naik penyata broker dan log trade klien di dashboard; bot akan bagi ringkasan di sini.",
        "reb.summary": "📒 <b>Rebate audit</b> · {broker} · {period}\nDijangka ${expected:,.2f} · dibayar ${paid:,.2f}\n<b>Kekurangan ${shortfall:,.2f}</b> pada {flagged} baris, {accounts} akaun\n{missing} akaun hilang · {rate} kadar ditukar senyap · {excluded} simbol dikecualikan",
        "reb.status": "Kekurangan tempoh semasa ({period}): <b>${shortfall:,.2f}</b> · larian #{id}",
        "ui.r_h": "Penyelarasan", "ui.r_lede": "Tampal atau muat naik dua fail CSV: penyata rebate broker (apa yang dibayar) dan log trade klien (apa yang ditrade). Tajuk lajur dipadankan secara longgar — account/login, symbol/instrument, lots/volume, rebate/paid.",
        "ui.r_broker": "Broker", "ui.r_period": "Tempoh", "ui.r_rate": "Kadar lalai $ setiap lot", "ui.r_overrides": "Kadar ikut simbol", "ui.r_tiers": "Tier volum",
        "ui.r_overrides_ph": "XAUUSD=8, EURUSD=6", "ui.r_tiers_ph": "100:7.5, 500:8",
        "ui.r_stmt": "Penyata broker (CSV)", "ui.r_log": "Log trade klien (CSV)", "ui.r_file": "atau muat naik fail",
        "ui.r_run": "Selaraskan", "ui.r_sample": "Guna contoh", "ui.r_expected": "Dijangka", "ui.r_paid": "Dibayar", "ui.r_shortfall": "Kekurangan",
        "ui.r_lines": "{n} baris ditanda", "ui.r_accounts": "{n} akaun", "ui.r_overpaid": "lebihan ${n:,.2f}",
        "ui.r_diff": "Jadual perbezaan", "ui.r_sort": "susun", "ui.r_kind": "Jenis", "ui.r_account": "Akaun", "ui.r_lots": "Lot", "ui.r_ratecol": "Kadar", "ui.r_implied": "Kadar tersirat",
        "ui.r_k_shortfall": "kekurangan", "ui.r_k_missing_account": "akaun hilang", "ui.r_k_silent_rate_change": "kadar ditukar senyap",
        "ui.r_k_excluded_symbol": "simbol dikecualikan", "ui.r_k_overpaid": "lebihan", "ui.r_k_ok": "tepat",
        "ui.r_pdf": "⬇ PDF pertikaian", "ui.r_runs": "Larian sebelum ini", "ui.r_norun": "Belum ada larian disimpan. Log masuk supaya setiap larian dan PDF-nya kekal di sini.",
        "ui.r_err_stmt": "Penyata: {err}", "ui.r_err_log": "Log trade: {err}", "ui.r_err_rate": "Kadar: {err}",
        # #11 churn
        "chn.usage": "Guna: <code>/ibchurn</code> — klien paling berisiko dari larian dashboard terakhir anda · <code>/ibchurn AKAUN</code> — butiran satu klien.",
        "chn.none": "Belum ada larian. Muat naik log trade klien di /p/churn-radar; bot akan senaraikan siapa yang perlu dihubungi.",
        "chn.top": "📡 <b>Churn radar</b> · {n} klien · setakat {as_of}\n🔴 {risk} berisiko · 🟡 {watch} pantau · 🟢 {healthy} sihat\nHasil berisiko: <b>${at_risk:,.0f}</b> daripada ${rev:,.0f} sebulan\n\n<b>Hubungi dahulu:</b>",
        "chn.row": "{icon} <code>{account}</code> {prob}% · ${at_risk:,.0f} · {flags}",
        "chn.detail": "{icon} <b>Klien {account}</b> · {prob}% ({band})\nVolum: {lots_recent:g} lot 30 hari ini vs {lots_prior:g} sebelum · susut {decay}%\nSenyap {days_since} hari (skor {dormancy}%) · terakhir {last_at}\nMartingale {martingale}% · Tekanan {stress}% (streak rugi {worst_streak}, drawdown ${drawdown:,.0f})\nHasil berisiko: <b>${at_risk:,.0f}</b>",
        "chn.no_client": "Akaun {account} tiada dalam larian terakhir.",
        "chn.band_risk": "berisiko", "chn.band_watch": "pantau", "chn.band_healthy": "sihat",
        "chn.f_decay": "volum susut", "chn.f_dormancy": "dorman", "chn.f_martingale": "martingale", "chn.f_stress": "tekanan",
        "chn.do": "Cadangan:",
        "ui.n_h": "Imbas buku klien", "ui.n_lede": "Tampal atau muat naik log trade klien (account, close time, symbol, lots, profit; balance jika ada). Setiap klien diskor pada empat isyarat dan disusun ikut hasil berisiko — klien bervolum tinggi pada 40% lebih penting daripada klien dorman pada 90%.",
        "ui.n_log": "Log trade klien (CSV)", "ui.n_rate": "Rebate $ setiap lot", "ui.n_asof": "Setakat (YYYY-MM-DD, pilihan)", "ui.n_run": "Imbas", "ui.n_sample": "Guna contoh",
        "ui.n_clients": "Klien", "ui.n_at_risk": "Hasil berisiko / 30 hari", "ui.n_rev": "daripada ${rev:,.0f} sebulan", "ui.n_bands": "{risk} berisiko · {watch} pantau · {healthy} sihat",
        "ui.n_book": "Buku klien", "ui.n_prob": "Kebarangkalian", "ui.n_signals": "Isyarat", "ui.n_lots30": "Lot 30h", "ui.n_prior": "sebelum", "ui.n_since": "Senyap", "ui.n_days": "hari",
        "ui.n_free": "Tier percuma tunjuk 10 klien teratas mengikut hasil berisiko; {n} lagi dalam larian ini. PRO buka semuanya.",
        "ui.n_detail": "Butiran klien", "ui.n_back": "← Buku", "ui.n_open": "Buka",
        "ui.n_log_h": "Log intervensi", "ui.n_note": "Apa yang dicuba, dan apa jadi", "ui.n_note_ph": "Telefon 12 Sep — kata platform lambat; hantar panduan VPS. Volum naik semula minggu berikut.", "ui.n_add": "Simpan nota",
        "ui.n_nonotes": "Belum ada nota untuk klien ini.", "ui.n_runs": "Larian sebelum ini", "ui.n_norun": "Log masuk supaya setiap larian dan log intervensi kekal di sini.",
        "ui.n_err": "Log trade: {err}",
        # #12 broker comparator
        "bc.usage": "Guna: <code>/goldspread</code> — kad perbandingan semasa · <code>/goldspread 1.0 overnight</code> — kos untuk saiz lot dan tempoh (intraday, overnight, week, month, atau bilangan malam).",
        "bc.head": "🥇 <b>Kos XAUUSD mengikut broker</b> · {lots:g} lot · {nights} malam\nSpot sekarang {mid} · spread suapan kami {spread}\n",
        "bc.row": "{rank}. <b>{name}</b> ({account}) — <b>${total:,.2f}</b> · spread ${spread:,.2f} + komisen ${commission:,.2f} + swap ${swap:,.2f}{obs}",
        "bc.obs": " · 👥 {n} pemerhatian",
        "bc.foot": "Nilai diterbitkan setakat {date}; sahkan dengan broker anda. Kos swap ikut arah long. {link}",
        "bc.link": "Daftar melalui pautan IB: {url}",
        "bc.nolink": "Log masuk dashboard untuk letak pautan IB anda pada kad ini.",
        "ui.b_h": "Perbandingan kos XAUUSD", "ui.b_lede": "Spread, komisen dan swap setiap broker untuk emas, dijadikan satu angka kos seunit lot untuk saiz dan tempoh pegangan anda. Nilai diterbitkan setakat {date}; pemerhatian komuniti menggantikannya bila cukup tiga. Sahkan dengan broker anda.",
        "ui.b_lots": "Saiz lot", "ui.b_nights": "Malam dipegang", "ui.b_side": "Arah", "ui.b_calc": "Kira",
        "ui.b_spot": "Spot sekarang", "ui.b_feed": "Spread suapan kami", "ui.b_cheapest": "Paling murah",
        "ui.b_rank": "#", "ui.b_broker": "Broker", "ui.b_account": "Akaun", "ui.b_spread": "Spread $/oz", "ui.b_comm": "Komisen / lot", "ui.b_swap": "Swap / malam",
        "ui.b_slip": "Slippage", "ui.b_total": "Kos {lots:g} lot · {nights} malam", "ui.b_src": "Sumber", "ui.b_published": "diterbitkan", "ui.b_observed": "diperhatikan ({n})",
        "ui.b_card_h": "Kad rujukan", "ui.b_card_lede": "Kad awam yang membawa pautan IB anda. Kongsi ke mana-mana group.",
        "ui.b_ref": "Pautan IB anda", "ui.b_ref_name": "Nama IB (pilihan)", "ui.b_save": "Simpan", "ui.b_card": "Buka kad", "ui.b_card_signin": "Log masuk untuk letak pautan IB anda pada kad.",
        "ui.b_obs_h": "Lapor spread yang anda ukur", "ui.b_obs_lede": "Buka platform anda, baca spread XAUUSD sekarang dalam dolar seauns (contoh 0.18), dan slippage terakhir jika ada. Tiga laporan menggantikan angka yang diterbitkan.",
        "ui.b_obs_spread": "Spread ($/oz)", "ui.b_obs_slip": "Slippage ($/oz, pilihan)", "ui.b_obs_btn": "Hantar", "ui.b_obs_ok": "Terima kasih — direkod.", "ui.b_obs_signin": "Log masuk untuk lapor.",
        "ui.b_obs_bad": "Spread mesti nombor antara 0 dan 5.",
        "ui.b_card_title": "Kos XAUUSD mengikut broker", "ui.b_card_by": "disusun oleh {name}", "ui.b_card_cta": "Daftar melalui pautan ini", "ui.b_card_note": "Kos untuk {lots:g} lot dipegang {nights} malam. Nilai diterbitkan setakat {date}. Sahkan dengan broker anda.",
        "flow.bc_lots": "🥇 <b>Broker Comparator</b>\nSaiz lot?", "flow.bc_nights": "Dipegang berapa malam?",
        # #13 links
        "lk.usage": "Guna: <code>/newlink CHANNEL [URL]</code> — cipta pautan pendek dijejak (URL lalai: pautan IB anda dari Broker Comparator) · <code>/funnel [7|30|90]</code> — klik, daftar, deposit, lot pertama setiap channel.",
        "lk.created": "🔗 <b>{channel}</b>\n{short}\n→ {url}\n\nKongsi pautan pendek itu; setiap klik dikira. Log daftar/deposit/lot di dashboard.",
        "lk.exists": "Channel <b>{channel}</b> sudah ada pautan: {short}",
        "lk.no_url": "Tiada URL. Hantar <code>/newlink {channel} https://…</code> atau simpan pautan IB anda di /p/broker-comparator.",
        "lk.limit": "Tier percuma: {n} pautan dijejak. Padam satu di dashboard atau naik ke PRO.",
        "lk.none": "Belum ada pautan. Hantar <code>/newlink telegram https://…</code> untuk mula.",
        "lk.funnel": "📈 <b>Funnel {days} hari</b>\nKlik {click} → daftar {signup} → deposit {deposit} → lot pertama {first_lot}{rate}\n",
        "lk.rate": " · klik→lot {pct:.1f}%",
        "lk.row": "• <b>{channel}</b> {click}/{signup}/{deposit}/{first_lot}",
        "ui.k_h": "Pengurus pautan", "ui.k_lede": "Satu pautan pendek setiap channel — Telegram, group WhatsApp, TikTok, YouTube, landing page. Setiap klik dikira di sini. Portal broker tak panggil balik, jadi daftar, deposit dan lot pertama anda log sendiri: borang di bawah, atau tampal laporan portal.",
        "ui.k_channel": "Channel", "ui.k_url": "URL destinasi (pautan IB anda)", "ui.k_make": "Cipta pautan", "ui.k_short": "Pautan pendek", "ui.k_clicks": "Klik", "ui.k_del": "Padam",
        "ui.k_free": "Tier percuma: {n} pautan. Padam satu untuk cipta yang baharu.", "ui.k_nolinks": "Belum ada pautan. Cipta satu setiap channel.",
        "ui.k_funnel": "Funnel", "ui.k_range": "Julat", "ui.k_days": "{n} hari", "ui.k_signups": "Daftar", "ui.k_deposits": "Deposit", "ui.k_lots": "Lot pertama",
        "ui.k_conv": "Klik → lot", "ui.k_best": "Channel terbaik", "ui.k_none": "tiada lagi",
        "ui.k_log_h": "Log peringkat", "ui.k_log_lede": "Bila portal broker tunjuk daftar, deposit atau lot pertama baharu, catat di sini pada channel yang betul.",
        "ui.k_stage": "Peringkat", "ui.k_count": "Bilangan", "ui.k_log": "Catat", "ui.k_s_signup": "daftar", "ui.k_s_deposit": "deposit pertama", "ui.k_s_first_lot": "lot pertama", "ui.k_s_click": "klik",
        "ui.k_csv_h": "Atau tampal laporan portal", "ui.k_csv_lede": "Lajur: channel, stage, count (pilihan), date (pilihan). Channel mesti sepadan dengan nama pautan.",
        "ui.k_csv_ph": "channel,stage,count\ntelegram,signup,4\ntelegram,deposit,2\ntiktok,signup,9",
        "ui.k_import": "Import", "ui.k_imported": "{n} baris diimport; {skipped} channel tak dikenali dilangkau.",
        "ui.k_err": "Laporan: {err}", "ui.k_bad": "Channel dan URL diperlukan.", "ui.k_signin": "Log masuk untuk cipta pautan dan lihat funnel anda.",
        "ui.k_table": "Perbandingan channel", "ui.k_ctr1": "daftar/klik", "ui.k_ctr2": "deposit/daftar", "ui.k_ctr3": "lot/deposit",
        "flow.lk_channel": "🥇 <b>Link Tracker</b>\nNama channel? (contoh <code>telegram</code>, <code>tiktok</code>)", "flow.lk_url": "URL destinasi? Langkau = pautan IB anda yang disimpan.",
        # scanners
        "scan.score": "skor", "scan.subject": "Subjek",
        "scan.verdict_high": "RISIKO TINGGI", "scan.verdict_caution": "BERHATI-HATI", "scan.verdict_low": "RISIKO RENDAH",
        "scan.more": "… {n} lagi penemuan di dashboard.", "scan.clean": "Tiada bendera dijumpai dalam teks ini. Itu bukan bukti selamat.",
        "scan.saved": "Disimpan sebagai imbasan #{n} — sejarah dan senarai pantau ada di dashboard.",
        "scan.disclaimer": "Pendidikan sahaja. Bukan nasihat kewangan.",
        "scan.usage_audit": "Guna: <code>/audit @nama_bot [apa yang bot itu kata]</code>\nContoh: <code>/audit @wallet_verify_b0t hantar seed phrase untuk claim</code>",
        "scan.usage_copy": "Guna: <code>/copyaudit BROKER [SPREAD_PIP] [LOT_SEBULAN]</code>\nContoh: <code>/copyaudit exness 2 10</code>",
        "scan.usage_scan": "Guna: <code>/scan TEKS</code> — tampal pitch signal (sekurang-kurangnya satu ayat).",
        "scan.usage_influencer": "Guna: <code>/influencer @handle [teks post atau DM]</code>",
        "scan.tail_audit": "Semak: nama berakhir 'bot', dipaut dari laman rasmi, tak pernah minta seed phrase atau yuran.",
        "scan.tail_copy": "Sahkan nombor lesen di daftar pengawal selia sebelum deposit.",
        "scan.tail_scan": "Minta akaun Myfxbook/FX Blue yang disahkan. Tangkapan skrin bukan bukti.",
        "scan.regs": "Pengawal selia dalam jadual kami: {regs}",
        "scan.cost": "Kos spread: {pips:g} pip × {lots:g} lot ≈ <b>${monthly:,.0f}/bulan</b> · ${yearly:,.0f}/tahun",
        "scan.demand": "Minta daripada mereka:",
        "scan.ib_links": "🔗 {n} pautan rujukan broker dijumpai — mereka dibayar bila anda deposit.",
    },
    "en": {
        "nav.products": "Tools", "nav.dashboard": "Dashboard", "nav.account": "Account",
        "nav.signin": "Sign in", "nav.signout": "Sign out", "nav.admin": "Admin",
        "nav.cta": "Open bot", "nav.lang": "BM",
        "hero.badge": "Since {since} · SAMBANGGOLD · 18 gold tools",
        "hero.title": "Gold tools, transparent.", "hero.title2": "Two surfaces.",
        "hero.subtitle": "Every tool answers in Telegram and has its own page here. One Telegram account links the two. All have a free tier; none is locked at the door.",
        "hero.cta_primary": "Open the Telegram bot", "hero.cta_secondary": "See every tool",
        "hero.note": "Education only. Not financial advice.",
        "stats.products": "Tools", "stats.live": "Live", "stats.free": "Free tiers", "stats.since": "Since",
        "doors.title": "Two ways to use it", "doors.subtitle": "Same tool, same free tier. Pick where you want the answer to land.",
        "doors.a_title": "🤖 In Telegram", "doors.a_body": "One command, one answer. Alerts land in your chat.", "doors.a_cta": "Open bot",
        "doors.b_title": "🌐 On the dashboard", "doors.b_body": "History, settings, CSV export. Everything a chat cannot keep.", "doors.b_cta": "Sign in",
        "grid.title": "Eighteen tools", "grid.subtitle": "{live} are live. {queued} are queued — spec written, page reserved.",
        "grid.live": "Live", "grid.queued": "Queued", "grid.open": "Open",
        "faq.title": "FAQ",
        "faq.q1": "Do I have to pay?", "faq.a1": "No. Every tool has a fully working free tier. Paid tiers sell scale and automation only.",
        "faq.q2": "Why a Telegram account?", "faq.a2": "So bot alerts and dashboard history are one list. You can also sign up by email and link Telegram later.",
        "faq.q3": "Where does the price come from?", "faq.a3": "Binance PAXGUSDT (real bid and ask) with Yahoo Finance GC=F as fallback. Both free and public.",
        "faq.q4": "Is this financial advice?", "faq.a4": "No. Education only. Verify every price with your own broker.",
        "signin.title": "Sign in", "signin.subtitle": "Telegram, email, or Google. No password.",
        "signin.telegram": "Sign in with Telegram", "signin.telegram_hint": "This button remembers the last Telegram account. To switch: Telegram app → Settings → Privacy & Security → Websites → disconnect this site.",
        "signin.email_label": "Your email", "signin.email_cta": "Send 8-digit code",
        "signin.email_hint": "We email you an 8-digit code. Valid for 10 minutes.",
        "signin.google": "Continue with Google", "signin.google_soon": "Coming soon",
        "signin.or": "or",
        "verify.title": "Check your email", "verify.subtitle": "An 8-digit code was sent to {email}.",
        "verify.code_label": "Code", "verify.cta": "Verify & enter", "verify.resend": "Resend",
        "verify.wrong": "Wrong or expired code. Try again.", "verify.too_many": "Too many attempts. Request a new code.",
        "verify.cooldown": "Wait a minute before requesting another code.", "verify.bad_email": "Invalid email.",
        "verify.mail_down": "Email cannot be sent right now. Use Telegram, or try again shortly.",
        "verify.sent": "Code sent.", "verify.dev_code": "Dev mode — your code: {code}",
        "google.title": "Google — coming soon", "google.body": "Google sign-in is being set up. Use Telegram or email for now.",
        "dash.title": "Member dashboard", "dash.subtitle": "Your tools, your alerts, your record.",
        "dash.rank": "Current rank", "dash.member_since": "Member since", "dash.upgrade": "Move up to A-Team for automation",
        "dash.alerts": "Armed alerts", "dash.triggers": "Alerts fired", "dash.saved": "Saved comparisons", "dash.linked": "Telegram linked",
        "dash.live": "Live tools", "dash.queued": "Queued", "dash.open": "Open tool",
        "dash.link_tg": "Link Telegram so alerts land in your chat.", "dash.link_email": "Add an email so you can sign in without Telegram.",
        "dash.not_linked": "Not linked",
        "account.title": "Account", "account.email": "Email", "account.telegram": "Telegram", "account.lang": "Language",
        "account.none": "None", "account.signout": "Sign out", "account.admin": "You are admin. Every feature is open.",
        "admin.title": "Admin", "admin.subtitle": "Every account, email and Telegram link.",
        "admin.users": "Accounts", "admin.emails": "With email", "admin.telegrams": "With Telegram", "admin.starts": "Bot /start",
        "admin.export": "Export CSV", "admin.col_email": "Email", "admin.col_tg": "Telegram", "admin.col_name": "Name",
        "admin.col_lang": "Lang", "admin.col_created": "Joined", "admin.col_last": "Last sign-in",
        "product.bot_half": "Telegram half", "product.web_half": "Dashboard half", "product.free": "Free tier",
        "product.live_note": "Live below — the same numbers the bot returns.",
        "product.soon": "Panels come online as each view is wired to data.",
        "product.queued": "Queued — the spec is written, the surface is reserved.",
        "product.upsell": "Upgrade", "product.upsell_note": "Paid tiers sell scale and automation only, never basic access.",
        "product.back": "All tools", "product.signin": "Sign in to save and export.",
        "footer.legal": "Legal", "footer.risk": "Risk disclosure", "footer.rights": "Education only. Not financial advice.",
        "risk.strip": "Trading gold, forex and CFDs on margin carries a high level of risk and you could lose more than your initial deposit. Past performance is not indicative of future results. All content is for education only and is not financial advice. Verify every price with your broker.",
        "mail.subject": "Your {brand} sign-in code: {code}",
        "mail.body": "Your sign-in code: {code}\n\nValid for 10 minutes. If you did not request it, ignore this email.\n\n{brand} · Education only. Not financial advice.",
        "bot.pick_lang": "🌐 Choose your language / Pilih bahasa anda:",
        "bot.lang_set": "Language set to English.",
        "bot.welcome": "<b>{brand}</b>. 18 gold tools, each answering here and on the dashboard.\n\nAll have a free tier. None is locked at the door.\n\n⚠️ CFD trading carries high risk. Education only, not financial advice.",
        "bot.menu": "What do you want to do?",
        "bot.btn_tools": "🥇 Try a free tool", "bot.btn_dash": "🌐 Open dashboard", "bot.btn_faq": "❓ FAQ",
        "bot.btn_channel": "📢 Public channel", "bot.btn_back": "⬅️ Back", "bot.btn_menu": "⬅️ Main Menu",
        "bot.btn_try": "▶️ Try an example", "bot.btn_open": "🌐 Open on dashboard", "bot.btn_share": "📤 Share", "bot.btn_again": "🔁 Try again",
        "bot.btn_more": "🔮 See what is queued",
        "bot.tools": "<b>Tools that are live</b>\nPick one. Each is free.",
        "bot.queued": "<b>Queued</b>\nSpec written, page reserved. The bot answers once each is live.",
        "bot.tool_card": "{emoji} <b>{name}</b>\n{solution}\n\n<b>Free tier:</b> {free}\n<b>Command:</b> <code>{command}</code>",
        "bot.faq": "<b>FAQ</b>\n\n<b>Do I have to pay?</b> No. Every tool has a fully working free tier.\n\n<b>Why Telegram?</b> So alerts here and history on the dashboard are one list.\n\n<b>Price data?</b> Binance PAXGUSDT, Yahoo GC=F fallback. Free and public.\n\n<b>Financial advice?</b> No. Education only.",
        "bot.help": "<b>Commands</b>", "bot.help_tail": "/start — menu · /language — switch language · /dashboard — dashboard link\n\nEducation only. Not financial advice.",
        "bot.dash": "Your dashboard. Sign in with Telegram — same account, same alert list.",
        "bot.unknown": "Unknown command. Send /start for the menu.",
        "bot.queued_reply": "{emoji} <b>{name}</b> — queued.\n{solution}",
        "bot.result_tail": "Save, export and compare on the dashboard.",
        "bot.share_text": "I use {brand} for gold. Try it free:",
        "cal.title": "📅 <b>Gold calendar</b>",
        "cal.next": "Next red USD events", "cal.none": "No red events in this week's feed.",
        "cal.fomc": "Next FOMC", "cal.holiday": "Next CME holiday", "cal.season": "This month ({n}-year average)",
        "cal.season_line": "return {ret:+.1f}% · range {rng:.1f}%",
        "cal.on": "🔔 30-minute alert: <b>ON</b>", "cal.off": "🔕 30-minute alert: <b>OFF</b>",
        "cal.btn_on": "🔔 Turn alerts on", "cal.btn_off": "🔕 Turn alerts off",
        "cal.push": "⏰ <b>{title}</b> in 30 minutes ({when} MYT).\nSpreads usually widen. Education only.",
        "cal.need_chat": "Alerts need a Telegram chat. Open the bot and send /calendar_alert.",
        "cal.spread_note": "Spread is sampled every 5 minutes; per-event history builds from here.",

        "signin.no_username": "The Telegram button appears once TELEGRAM_BOT_USERNAME is set on the server.",
        "watch.usage": "Usage:\n<code>/watch XAUUSD</code> — live price, spread and entry/stop levels\n<code>/watch XAUUSD above 2450</code> — alert when the <i>ask</i> reaches 2450\n<code>/watch XAUUSD below 2380</code> — alert when the <i>bid</i> falls to 2380\n<code>/watch list</code> · <code>/watch clear</code>\n\nOr tap ▶️ Start and the bot asks one thing at a time.",
        "watch.none": "No alerts armed.", "watch.list": "<b>Armed alerts</b>", "watch.cleared": "Cleared {n} alert(s).",
        "watch.only_gold": "Only gold for now (<code>XAUUSD</code>). Multi-pair is on the PRO tier.",
        "watch.feed_down": "Feed unavailable right now ({err}). Try again in a minute.",
        "watch.armed": "Armed: ", "watch.level_num": "Level must be a number.", "watch.need_chat": "Alerts need a Telegram chat to fire into.",
        "watch.ok": "✅ Alert #{id} armed: {sym} {dir} {level} (fires on the {side}).\nNow: bid {bid} · ask {ask}",
        "watch.spread": "Spread {spread} · {src}", "watch.nobook": "n/a (no order book)",
        "watch.long": "Long: enter {e}, stop {s}", "watch.short": "Short: enter {e}, stop {s}",
        "watch.above": "above", "watch.below": "below",
        "watch.d_armed": "Alert #{id} armed.", "watch.d_updated": "Threshold updated.", "watch.d_disarmed": "Alert disarmed.",
        "watch.fire": "🔔 <b>XAUUSD {dir} {level}</b> — {side} now {price} ({src})\nEducational research only. Verify with your broker.",
        "prop.usage": "Usage: <code>/propcalc FEE SIZE PASS%</code>\nExample: <code>/propcalc 500 100000 15</code> — a $500 fee on a $100k account with a 15% chance of passing.\n\nOr tap ▶️ Start and the bot asks one thing at a time.",
        "prop.reply": "{tone} <b>EV {ev}</b> on a {cost} fee ({roi} ROI)\nFirst payout if funded: {payout} ({target} target × {split} split on {size})\nBreakeven pass rate: <b>{be}</b> — you said {pass}\n\nPaste the firm's terms on the dashboard for the rule scan.",
        "ib.usage": "Usage: <code>/ibcalc LOTS RATE [CLIENTS] [CLAWBACK%]</code>\nExample: <code>/ibcalc 40 7 25 5</code> — 25 clients trading 40 lots a month at $7 a lot with 5% clawback.\n\nOr tap ▶️ Start and the bot asks one thing at a time.",
        "ib.reply": "<b>{net} net per month</b> · {annual} a year\nGross {gross} from {clients} client(s) × {lots:g} lots × ${rate:g}\nClawback {claw} · margin {margin}\n\nAdd compliance cost, payout threshold and hold period on the dashboard to see when the first cash lands.",
        "flow.start": "▶️ Start", "flow.example": "💡 Example", "flow.cancel": "✖ Cancel", "flow.skip": "⏭ Skip",
        "flow.cancelled": "Cancelled. Send /start for the menu.", "flow.not_number": "Numbers only, e.g. <code>2450</code>. Try again.",
        "flow.chosen": "{prompt}\n\n✅ {value}", "flow.typed": "Or type your own value.",
        "flow.watch_mode": "🥇 <b>Gold Watch</b>\nWhat do you want?",
        "flow.watch_price": "📈 Price now", "flow.watch_above": "🔔 Alert when it rises above…", "flow.watch_below": "🔔 Alert when it falls below…",
        "flow.watch_level": "Enter the price level (e.g. <code>2450</code>).",
        "flow.prop_fee": "🏛 <b>Prop Firm Challenge</b>\nChallenge fee (USD)?",
        "flow.prop_size": "Account size (USD)?", "flow.prop_pass": "Your chance of passing (%)? Industry: 10–25%.",
        "flow.ib_lots": "🥇 <b>IB Revenue</b>\nLots per client per month?", "flow.ib_rate": "Rebate (USD) per lot?",
        "flow.ib_clients": "How many active clients?", "flow.ib_claw": "Clawback (%)?",
        "flow.audit_handle": "🔒 <b>Bot Scam Detector</b>\nSend the bot's username (e.g. <code>@wallet_verify_b0t</code>).",
        "flow.audit_text": "Paste what the bot said — or Skip.",
        "flow.copy_broker": "🔒 <b>Copy-Trade Audit</b>\nWhich broker? Pick one or type the name.",
        "flow.copy_spread": "Typical spread (pips)? Or Skip.", "flow.copy_lots": "Lots you copy per month? Or Skip.",
        "flow.scan_text": "💱 <b>Red-Flag Scanner</b>\nPaste the signal pitch here — the channel post, the DM, or the sales page.",
        "flow.inf_handle": "🔒 <b>Influencer Audit</b>\nThe influencer's handle (e.g. <code>@gold_guru</code>)?",
        "flow.inf_text": "Paste their post, bio or DM, links included — or Skip.",
        "ui.calc": "Calculate", "ui.calc_save": "Calculate & save", "ui.verdict": "Verdict", "ui.rule": "Rule", "ui.where": "Where",
        "ui.why": "Why it matters", "ui.flag": "Flag", "ui.history": "History", "ui.when": "When (UTC)", "ui.source": "Source",
        "ui.price": "Price", "ui.never": "never", "ui.month": "Month", "ui.event": "Event", "ui.forecast": "Forecast", "ui.previous": "Previous",
        "ui.w_live": "Live gold", "ui.w_mid": "XAUUSD mid", "ui.w_bidask": "Bid / ask", "ui.w_bidask_note": "the prices you would actually get",
        "ui.w_nobook": "no order book on this source", "ui.w_peroz": "per oz", "ui.w_stopnote": "Stops are 0.5% widened by the spread — a starting point, not a signal.",
        "ui.w_feed_err": "Feed unavailable: {err}", "ui.w_armed": "Armed alerts",
        "ui.w_signin": "Sign in with Telegram (top right) to see the alerts you armed in the bot, edit thresholds and export history. One account, both surfaces.",
        "ui.w_dir": "Direction", "ui.w_above": "above — fires on the ask", "ui.w_below": "below — fires on the bid", "ui.w_level": "Level",
        "ui.w_arm": "Arm alert", "ui.w_pair": "Pair", "ui.w_save": "Save", "ui.w_disarm": "Disarm",
        "ui.w_none": "Nothing armed. Arm one here or send <code>/watch XAUUSD above 2450</code> to the bot — same list.",
        "ui.w_hist": "Alert history", "ui.w_fired": "Fired (UTC)", "ui.w_alert": "Alert", "ui.w_export": "⬇ Export history (.csv)",
        "ui.w_nohist": "No triggers yet. Each one is recorded with the price and spread at fire time — the journal a chat log cannot give you.",
        "ui.p_calc": "Calculator", "ui.p_firm": "Firm", "ui.p_fee": "Challenge fee $", "ui.p_size": "Account size $", "ui.p_pass": "Your pass chance %",
        "ui.p_target": "Profit target %", "ui.p_split": "Profit split %", "ui.p_resets": "Resets bought", "ui.optional": "optional",
        "ui.p_ev": "Expected value", "ui.p_on_paid": "{roi} on {cost} paid", "ui.p_breakeven": "Breakeven pass rate", "ui.p_entered": "you entered {p}",
        "ui.p_first": "First payout if funded", "ui.p_target_split": "{target} target × {split} split",
        "ui.p_share": "A shareable link to this exact result is the address bar. Industry pass rates sit around 10–25%; if your breakeven is above that band, the fee is priced against you.",
        "ui.p_scan": "Rule scan", "ui.p_paste": "Paste the challenge terms", "ui.p_paste_ph": "Paste the firm's rules page or T&Cs here…", "ui.p_scan_btn": "Scan terms",
        "ui.p_reds": "{r} red · {y} yellow", "ui.p_chars": "{n} characters scanned", "ui.why_fail": "Why it fails people",
        "ui.p_clean": "None of the known failure rules matched. That is not a clean bill — read the drawdown section yourself.",
        "ui.p_saved": "Saved comparisons", "ui.paid": "Paid", "ui.size": "Size", "ui.pass": "Pass", "ui.breakeven": "Breakeven",
        "ui.p_nosave": "Nothing saved yet. Use <em>Calculate & save</em> to line firms up side by side. Comparisons live in this browser session.",
        "ui.i_model": "Revenue model", "ui.i_broker": "Broker", "ui.i_lots": "Lots per client / month", "ui.i_rate": "Rebate $ per lot", "ui.i_clients": "Active clients",
        "ui.i_claw": "Clawback %", "ui.i_comp": "Compliance cost $ / month", "ui.i_thresh": "Payout threshold $", "ui.i_hold": "Hold period (days)",
        "ui.i_net": "Net per month", "ui.i_net_note": "{annual} a year · {margin} margin", "ui.i_gross": "Gross rebate", "ui.i_gross_note": "−{claw} clawback · −{comp} compliance",
        "ui.i_first": "First cash lands", "ui.i_day": "day {d}", "ui.i_first_note": "{thresh} threshold + {days}-day hold",
        "ui.i_timeline": "Payout timeline", "ui.earned": "Earned", "ui.paid_out": "Paid out", "ui.held": "Held back", "ui.cumulative": "Cumulative paid",
        "ui.i_share": "Shareable link to this exact model: the address bar. The payout threshold and hold period are the two numbers to confirm in writing before you refer a single client.",
        "ui.i_checklist": "Compliance checklist", "ui.i_download": "⬇ Download the checklist (.txt)", "ui.i_saved": "Saved scenarios",
        "ui.rate": "Rate", "ui.clients": "Clients", "ui.net_month": "Net / month", "ui.annual": "Annual", "ui.first_cash": "First cash",
        "ui.i_nosave": "Nothing saved yet. Use <em>Calculate & save</em> to line brokers up side by side. Scenarios live in this browser session.",
        "ui.c_baseline": "Baseline spread", "ui.c_season": "Seasonality · 12 months", "ui.c_season_note": "{src} · average monthly return; bar height is the size of the move.",
        "ui.c_hist": "What the spread did last time", "ui.measured": "Measured", "ui.worst": "Worst spread", "ui.mean": "Mean", "ui.vs_base": "vs baseline",
        "ui.s_h_bot": "Audit a bot", "ui.s_h_copy": "Audit a copy-trade broker", "ui.s_h_scan": "Scan a signal pitch", "ui.s_h_inf": "Audit an influencer",
        "ui.audit": "Audit", "ui.scan": "Scan",
        "ui.s_ph_bot": "Paste the bot's welcome message, the link it sent, or the DM…", "ui.s_ph_copy": "Paste the pitch: 'copy my trades, 10% a month, sign up with my link…'",
        "ui.s_ph_scan": "Paste the whole pitch — the channel post, the DM, the sales page…", "ui.s_ph_inf": "Paste their post, bio, pinned message or DM, links included…",
        "ui.s_sub_bot": "Bot username", "ui.s_txt_bot": "Paste what the bot said (optional)", "ui.s_sub_copy": "Broker", "ui.s_txt_copy": "Paste the copy-trade pitch (optional)",
        "ui.s_sub_scan": "Channel or seller (optional)", "ui.s_txt_scan": "Paste the pitch", "ui.s_sub_inf": "Influencer handle", "ui.s_txt_inf": "Paste their post, bio or DM (optional)",
        "ui.s_spread": "Typical spread (pips)", "ui.s_lots": "Lots you copy per month", "ui.s_need_sub": "{label} is required.", "ui.s_need_text": "Paste the pitch first.",
        "ui.s_flags": "Flags", "ui.s_rgy": "red / yellow / good", "ui.s_reg": "Regulation", "ui.s_tier1": "Tier-1", "ui.s_offshore": "Offshore only", "ui.s_unknown": "Unknown",
        "ui.s_not_table": "not in our table", "ui.s_cost_year": "Spread cost / year", "ui.s_cost_note": "${m:,.0f} a month at {p:g} pips × {l:g} lots",
        "ui.s_ref": "Broker referral links", "ui.s_ref_note": "they get paid when you deposit", "ui.s_share": "Share link", "ui.s_community": "scanned {n}× by the community",
        "ui.s_checklist": "Checklist", "ui.s_verify": "Verify on the register", "ui.regulator": "Regulator", "ui.meaning": "What it means", "ui.register": "Register", "ui.open": "open ↗",
        "ui.s_trail": "Broker-promotion trail", "ui.s_watch": "Watchlist", "ui.scans": "Scans", "ui.latest": "Latest score", "ui.rescan": "Re-scan",
        "ui.s_run": "Run your own scan", "ui.s_scan_n": "scan #{n}",
        "ui.l_title": "Loss-report template", "ui.l_lede": "Lost money already? Fill this in and download the report in the shape the FTC, CFTC, IC3, SC Malaysia and BNM forms ask for.",
        "ui.l_handle": "Influencer handle", "ui.l_platform": "Platform", "ui.l_broker": "Broker / venue promoted", "ui.l_amount": "Amount lost", "ui.l_currency": "Currency",
        "ui.l_date": "Date(s)", "ui.l_story": "What happened, in order", "ui.l_story_ph": "First contact, what was promised, what you paid, what happened after…",
        "ui.l_download": "⬇ Download report.txt",
        "ver.usage": "Usage: <code>/verify GOLD PRICE [DATE] [TIME]</code>\nExample: <code>/verify GOLD 2431.5 2026-09-14 14:30</code> (MYT). No date = the last 24 hours.\n\nOr tap ▶️ Start and the bot asks one thing at a time.",
        "ver.bad_input": "Price must be a number; date YYYY-MM-DD; time HH:MM (MYT).",
        "ver.v_real": "REAL", "ver.v_borderline": "BORDERLINE", "ver.v_impossible": "IMPOSSIBLE", "ver.v_unverified": "UNVERIFIED",
        "ver.line_range": "Window range: {low} – {high} ({src}, {n} one-minute candles)",
        "ver.line_nearest": "Nearest candle: {at} MYT · low {low} · high {high}",
        "ver.line_gap": "Outside the range by ${gap} ({pct:.2f}%).",
        "ver.line_nodata": "No candles for this window. {err}",
        "ver.note": "PAXG is one ounce of gold on Binance; your broker may differ by a few dollars. BORDERLINE = within that tolerance. Ask for an account statement, not a screenshot.",
        "flow.ver_price": "🥇 <b>Signal Verifier</b>\nThe claimed fill price? (e.g. <code>2431.5</code>)",
        "flow.ver_date": "Date of the fill (YYYY-MM-DD, MYT)? Skip = the last 24 hours.",
        "flow.ver_time": "Time (HH:MM, MYT)? Skip = that whole day.",
        "ui.v_h": "Verify one fill", "ui.v_price": "Claimed price", "ui.v_date": "Date (MYT)", "ui.v_time": "Time (MYT)", "ui.v_side": "Side",
        "ui.v_any": "any", "ui.v_buy": "buy", "ui.v_sell": "sell", "ui.v_btn": "Verify",
        "ui.v_batch": "Batch verify", "ui.v_batch_label": "One claim per line: PRICE [DATE] [TIME] [buy|sell]",
        "ui.v_batch_ph": "2431.5 2026-09-14 14:30 buy\n2418.0 2026-09-14\n2455.2",
        "ui.v_batch_btn": "Verify all", "ui.v_need_lines": "Paste at least one line.",
        "ui.v_window": "Window", "ui.v_range": "Range", "ui.v_candles": "candles", "ui.v_gap": "Gap", "ui.v_claim": "Claim",
        "ui.v_nohist": "No checks yet. Every verdict is kept here with the candle window that produced it.",
        "ui.v_lede": "Paste the price from the signal screenshot. We check whether it was ever printed in Binance PAXGUSDT one-minute candles. Dates and times are MYT.",
        "reb.usage": "Usage: <code>/rebateaudit</code> — summary of your last dashboard run.\nOr a quick check: <code>/rebateaudit LOTS RATE PAID</code>, e.g. <code>/rebateaudit 42.5 8 300</code>.",
        "reb.quick": "{lots:g} lots × ${rate:g} = <b>${expected:,.2f}</b> expected · paid ${paid:,.2f} · {label} <b>${diff:,.2f}</b>",
        "reb.short": "shortfall", "reb.over": "overpaid", "reb.exact": "exact",
        "reb.none": "No runs yet. Upload the broker statement and the client trade log on the dashboard; the bot summarises here.",
        "reb.summary": "📒 <b>Rebate audit</b> · {broker} · {period}\nExpected ${expected:,.2f} · paid ${paid:,.2f}\n<b>Shortfall ${shortfall:,.2f}</b> across {flagged} lines, {accounts} accounts\n{missing} missing account · {rate} silent rate change · {excluded} excluded symbol",
        "reb.status": "Current-period shortfall ({period}): <b>${shortfall:,.2f}</b> · run #{id}",
        "ui.r_h": "Reconcile", "ui.r_lede": "Paste or upload two CSVs: the broker's rebate statement (what was paid) and the client trade log (what was traded). Headers are matched loosely — account/login, symbol/instrument, lots/volume, rebate/paid.",
        "ui.r_broker": "Broker", "ui.r_period": "Period", "ui.r_rate": "Default rate $ per lot", "ui.r_overrides": "Per-symbol rates", "ui.r_tiers": "Volume tiers",
        "ui.r_overrides_ph": "XAUUSD=8, EURUSD=6", "ui.r_tiers_ph": "100:7.5, 500:8",
        "ui.r_stmt": "Broker statement (CSV)", "ui.r_log": "Client trade log (CSV)", "ui.r_file": "or upload a file",
        "ui.r_run": "Reconcile", "ui.r_sample": "Load sample", "ui.r_expected": "Expected", "ui.r_paid": "Paid", "ui.r_shortfall": "Shortfall",
        "ui.r_lines": "{n} lines flagged", "ui.r_accounts": "{n} accounts", "ui.r_overpaid": "overpaid ${n:,.2f}",
        "ui.r_diff": "Diff table", "ui.r_sort": "sort", "ui.r_kind": "Kind", "ui.r_account": "Account", "ui.r_lots": "Lots", "ui.r_ratecol": "Rate", "ui.r_implied": "Implied rate",
        "ui.r_k_shortfall": "shortfall", "ui.r_k_missing_account": "missing account", "ui.r_k_silent_rate_change": "silent rate change",
        "ui.r_k_excluded_symbol": "excluded symbol", "ui.r_k_overpaid": "overpaid", "ui.r_k_ok": "exact",
        "ui.r_pdf": "⬇ Dispute PDF", "ui.r_runs": "Previous runs", "ui.r_norun": "No runs saved yet. Sign in so every run and its PDF stay here.",
        "ui.r_err_stmt": "Statement: {err}", "ui.r_err_log": "Trade log: {err}", "ui.r_err_rate": "Rate card: {err}",
        "chn.usage": "Usage: <code>/ibchurn</code> — clients most at risk from your last dashboard run · <code>/ibchurn ACCOUNT</code> — one client in detail.",
        "chn.none": "No runs yet. Upload the client trade log at /p/churn-radar; the bot lists who to call.",
        "chn.top": "📡 <b>Churn radar</b> · {n} clients · as of {as_of}\n🔴 {risk} at risk · 🟡 {watch} watch · 🟢 {healthy} healthy\nRevenue at risk: <b>${at_risk:,.0f}</b> of ${rev:,.0f} a month\n\n<b>Call first:</b>",
        "chn.row": "{icon} <code>{account}</code> {prob}% · ${at_risk:,.0f} · {flags}",
        "chn.detail": "{icon} <b>Client {account}</b> · {prob}% ({band})\nVolume: {lots_recent:g} lots last 30d vs {lots_prior:g} before · decay {decay}%\nQuiet {days_since} days (score {dormancy}%) · last {last_at}\nMartingale {martingale}% · Stress {stress}% (losing streak {worst_streak}, drawdown ${drawdown:,.0f})\nRevenue at risk: <b>${at_risk:,.0f}</b>",
        "chn.no_client": "Account {account} is not in the last run.",
        "chn.band_risk": "at risk", "chn.band_watch": "watch", "chn.band_healthy": "healthy",
        "chn.f_decay": "volume decay", "chn.f_dormancy": "dormant", "chn.f_martingale": "martingale", "chn.f_stress": "stress",
        "chn.do": "Suggested:",
        "ui.n_h": "Scan the client book", "ui.n_lede": "Paste or upload the client trade log (account, close time, symbol, lots, profit; balance if you have it). Every client is scored on four signals and ranked by revenue at risk — a high-volume client at 40% matters more than a dormant one at 90%.",
        "ui.n_log": "Client trade log (CSV)", "ui.n_rate": "Rebate $ per lot", "ui.n_asof": "As of (YYYY-MM-DD, optional)", "ui.n_run": "Scan", "ui.n_sample": "Load sample",
        "ui.n_clients": "Clients", "ui.n_at_risk": "Revenue at risk / 30 days", "ui.n_rev": "of ${rev:,.0f} a month", "ui.n_bands": "{risk} at risk · {watch} watch · {healthy} healthy",
        "ui.n_book": "Client book", "ui.n_prob": "Probability", "ui.n_signals": "Signals", "ui.n_lots30": "Lots 30d", "ui.n_prior": "prior", "ui.n_since": "Quiet", "ui.n_days": "days",
        "ui.n_free": "The free tier shows the top 10 clients by revenue at risk; {n} more in this run. PRO opens all of them.",
        "ui.n_detail": "Client detail", "ui.n_back": "← Book", "ui.n_open": "Open",
        "ui.n_log_h": "Intervention log", "ui.n_note": "What was tried, and what it did", "ui.n_note_ph": "Called 12 Sep — said the platform was slow; sent the VPS guide. Volume back up the week after.", "ui.n_add": "Save note",
        "ui.n_nonotes": "No notes for this client yet.", "ui.n_runs": "Previous runs", "ui.n_norun": "Sign in so every run and the intervention log stay here.",
        "ui.n_err": "Trade log: {err}",
        "bc.usage": "Usage: <code>/goldspread</code> — the current comparison card · <code>/goldspread 1.0 overnight</code> — cost for a lot size and holding period (intraday, overnight, week, month, or a number of nights).",
        "bc.head": "🥇 <b>XAUUSD cost by broker</b> · {lots:g} lot · {nights} night(s)\nSpot now {mid} · our feed spread {spread}\n",
        "bc.row": "{rank}. <b>{name}</b> ({account}) — <b>${total:,.2f}</b> · spread ${spread:,.2f} + commission ${commission:,.2f} + swap ${swap:,.2f}{obs}",
        "bc.obs": " · 👥 {n} observations",
        "bc.foot": "Published values as of {date}; verify with your broker. Swap cost assumes a long. {link}",
        "bc.link": "Sign up through the IB link: {url}",
        "bc.nolink": "Sign in on the dashboard to put your IB link on this card.",
        "ui.b_h": "XAUUSD cost comparison", "ui.b_lede": "Spread, commission and swap per broker for gold, turned into one cost-per-lot figure for your size and holding period. Published values as of {date}; community observations replace them once there are three. Verify with your broker.",
        "ui.b_lots": "Lot size", "ui.b_nights": "Nights held", "ui.b_side": "Side", "ui.b_calc": "Calculate",
        "ui.b_spot": "Spot now", "ui.b_feed": "Our feed spread", "ui.b_cheapest": "Cheapest",
        "ui.b_rank": "#", "ui.b_broker": "Broker", "ui.b_account": "Account", "ui.b_spread": "Spread $/oz", "ui.b_comm": "Commission / lot", "ui.b_swap": "Swap / night",
        "ui.b_slip": "Slippage", "ui.b_total": "Cost {lots:g} lot · {nights} nights", "ui.b_src": "Source", "ui.b_published": "published", "ui.b_observed": "observed ({n})",
        "ui.b_card_h": "Referral card", "ui.b_card_lede": "A public card that carries your IB link. Share it into any group.",
        "ui.b_ref": "Your IB link", "ui.b_ref_name": "IB name (optional)", "ui.b_save": "Save", "ui.b_card": "Open card", "ui.b_card_signin": "Sign in to put your IB link on the card.",
        "ui.b_obs_h": "Report the spread you measured", "ui.b_obs_lede": "Open your platform, read the XAUUSD spread right now in dollars per ounce (e.g. 0.18), and the last slippage if you have it. Three reports replace the published figure.",
        "ui.b_obs_spread": "Spread ($/oz)", "ui.b_obs_slip": "Slippage ($/oz, optional)", "ui.b_obs_btn": "Submit", "ui.b_obs_ok": "Thanks — recorded.", "ui.b_obs_signin": "Sign in to report.",
        "ui.b_obs_bad": "Spread must be a number between 0 and 5.",
        "ui.b_card_title": "XAUUSD cost by broker", "ui.b_card_by": "compiled by {name}", "ui.b_card_cta": "Sign up through this link", "ui.b_card_note": "Cost for {lots:g} lot held {nights} nights. Published values as of {date}. Verify with your broker.",
        "flow.bc_lots": "🥇 <b>Broker Comparator</b>\nLot size?", "flow.bc_nights": "Held for how many nights?",
        "lk.usage": "Usage: <code>/newlink CHANNEL [URL]</code> — mint a tracked short link (URL defaults to your IB link from Broker Comparator) · <code>/funnel [7|30|90]</code> — clicks, signups, deposits, first lots per channel.",
        "lk.created": "🔗 <b>{channel}</b>\n{short}\n→ {url}\n\nShare the short link; every click is counted. Log signups/deposits/lots on the dashboard.",
        "lk.exists": "Channel <b>{channel}</b> already has a link: {short}",
        "lk.no_url": "No URL. Send <code>/newlink {channel} https://…</code> or save your IB link at /p/broker-comparator.",
        "lk.limit": "Free tier: {n} tracked links. Delete one on the dashboard or go PRO.",
        "lk.none": "No links yet. Send <code>/newlink telegram https://…</code> to start.",
        "lk.funnel": "📈 <b>Funnel {days} days</b>\nClicks {click} → signups {signup} → deposits {deposit} → first lots {first_lot}{rate}\n",
        "lk.rate": " · click→lot {pct:.1f}%",
        "lk.row": "• <b>{channel}</b> {click}/{signup}/{deposit}/{first_lot}",
        "ui.k_h": "Link manager", "ui.k_lede": "One short link per channel — Telegram, WhatsApp group, TikTok, YouTube, landing page. Every click is counted here. Broker portals do not call back, so you log signups, deposits and first lots yourself: the form below, or paste the portal report.",
        "ui.k_channel": "Channel", "ui.k_url": "Destination URL (your IB link)", "ui.k_make": "Create link", "ui.k_short": "Short link", "ui.k_clicks": "Clicks", "ui.k_del": "Delete",
        "ui.k_free": "Free tier: {n} links. Delete one to create another.", "ui.k_nolinks": "No links yet. Create one per channel.",
        "ui.k_funnel": "Funnel", "ui.k_range": "Range", "ui.k_days": "{n} days", "ui.k_signups": "Signups", "ui.k_deposits": "Deposits", "ui.k_lots": "First lots",
        "ui.k_conv": "Click → lot", "ui.k_best": "Best channel", "ui.k_none": "none yet",
        "ui.k_log_h": "Log a stage", "ui.k_log_lede": "When the broker portal shows a new signup, deposit or first lot, record it here against the right channel.",
        "ui.k_stage": "Stage", "ui.k_count": "Count", "ui.k_log": "Log", "ui.k_s_signup": "signup", "ui.k_s_deposit": "first deposit", "ui.k_s_first_lot": "first lot", "ui.k_s_click": "click",
        "ui.k_csv_h": "Or paste the portal report", "ui.k_csv_lede": "Columns: channel, stage, count (optional), date (optional). Channel must match a link name.",
        "ui.k_csv_ph": "channel,stage,count\ntelegram,signup,4\ntelegram,deposit,2\ntiktok,signup,9",
        "ui.k_import": "Import", "ui.k_imported": "{n} rows imported; {skipped} unknown channels skipped.",
        "ui.k_err": "Report: {err}", "ui.k_bad": "Channel and URL are required.", "ui.k_signin": "Sign in to create links and see your funnel.",
        "ui.k_table": "Channel comparison", "ui.k_ctr1": "signup/click", "ui.k_ctr2": "deposit/signup", "ui.k_ctr3": "lot/deposit",
        "flow.lk_channel": "🥇 <b>Link Tracker</b>\nChannel name? (e.g. <code>telegram</code>, <code>tiktok</code>)", "flow.lk_url": "Destination URL? Skip = your saved IB link.",
        "scan.score": "score", "scan.subject": "Subject",
        "scan.verdict_high": "HIGH RISK", "scan.verdict_caution": "CAUTION", "scan.verdict_low": "LOW RISK",
        "scan.more": "… {n} more findings on the dashboard.", "scan.clean": "No flags found in this text. That is not proof it is safe.",
        "scan.saved": "Saved as scan #{n} — history and watchlist are on the dashboard.",
        "scan.disclaimer": "Education only. Not financial advice.",
        "scan.usage_audit": "Usage: <code>/audit @bot_username [what the bot said]</code>\nExample: <code>/audit @wallet_verify_b0t send your seed phrase to claim</code>",
        "scan.usage_copy": "Usage: <code>/copyaudit BROKER [SPREAD_PIPS] [LOTS_PER_MONTH]</code>\nExample: <code>/copyaudit exness 2 10</code>",
        "scan.usage_scan": "Usage: <code>/scan TEXT</code> — paste the signal pitch (at least one sentence).",
        "scan.usage_influencer": "Usage: <code>/influencer @handle [their post or DM]</code>",
        "scan.tail_audit": "Check: name ends in 'bot', linked from the official site, never asks for a seed phrase or a fee.",
        "scan.tail_copy": "Verify the licence number on the regulator's register before you deposit.",
        "scan.tail_scan": "Ask for a verified Myfxbook / FX Blue account. Screenshots are not proof.",
        "scan.regs": "Regulators in our table: {regs}",
        "scan.cost": "Spread cost: {pips:g} pips × {lots:g} lots ≈ <b>${monthly:,.0f}/month</b> · ${yearly:,.0f}/year",
        "scan.demand": "Demand from them:",
        "scan.ib_links": "🔗 {n} broker referral link(s) found — they get paid when you deposit.",
    },
}


def t(key, lang=DEFAULT_LANG, **kwargs):
    """Look a string up in `lang`, falling back to Bahasa Melayu, then to the key."""
    table = STRINGS.get(lang) or STRINGS[DEFAULT_LANG]
    text = table.get(key) or STRINGS[DEFAULT_LANG].get(key) or key
    return text.format(brand=BRAND["name"], since=BRAND["since"], **kwargs) if ("{" in text) else text


def rank_label(rank, lang=DEFAULT_LANG):
    return RANKS.get(rank, RANKS["public"]).get(lang) or RANKS["public"]["ms"]


def normalise_lang(code):
    """Telegram language codes → our two. Indonesian reads Malay comfortably."""
    code = (code or "").lower()
    if code.startswith(("ms", "id")):
        return "ms"
    if code.startswith("en"):
        return "en"
    return None
