"""Bahasa Melayu copy for every product in the registry.

The registry in ``products.py`` stays English (it is the spec and the contract).
This module carries the Malay wording of the user-facing fields. Product names,
rank names and the trading vocabulary Malaysians already use in English
(spread, lot, drawdown, prop firm, rebate, payout, broker, alert, signal) are
kept as they are. ``Product.view(lang)`` merges the two.
"""

MS = {
    "gold-watch": {
        "free_tier": "/watch emas tanpa had. Tak perlu akaun.",
        "problem": "Trader terlepas entry emas kerana spread dan slippage, dan kebanyakan channel emas Telegram adalah scam.",
        "solution": "Paras entry dan stop yang ambil kira spread, dari Binance PAXGUSDT dengan Yahoo GC=F sebagai sandaran.",
        "bot_commands": (
            ("/watch XAUUSD", "pasang alert emas yang ambil kira spread"),
            ("/watch list", "senarai alert yang anda pasang"),
        ),
        "dashboard_views": (
            "Sejarah alert — setiap cetusan dengan harga dan spread ketika itu",
            "Ubah paras setiap alert yang dipasang",
            "Eksport CSV untuk jurnal",
        ),
        "upsell": "/autopilot serta asas DCF dan COT.",
        "primary_why": "Satu arahan masuk, satu alert keluar — dashboard simpan sejarah yang chat tak boleh.",
    },
    "signal-verifier": {
        "free_tier": "Satu semakan setiap permintaan, tanpa had.",
        "problem": "Penjual signal emas hantar screenshot MT4 palsu dengan entry pilihan.",
        "solution": "Tarik sejarah tick Binance PAXGUSDT dan uji sama ada harga fill yang didakwa memang wujud.",
        "bot_commands": (("/verify GOLD HARGA", "uji fill yang didakwa — REAL atau IMPOSSIBLE"),),
        "dashboard_views": (
            "Arkib verdict dengan tetingkap tick untuk setiap semakan",
            "Semak beramai-ramai — tampal atau muat naik senarai fill",
            "Pautan verdict awam untuk dihantar balik ke group",
        ),
        "upsell": "PRO muat naik CSV dan laporan audit mingguan.",
        "primary_why": "Semakan patut berlaku dalam group tempat signal palsu itu dihantar.",
    },
    "prop-calculator": {
        "free_tier": "Kalkulator penuh dan arahan bot, tiada had.",
        "problem": "Trader bayar $500–$5,000 yuran challenge tanpa anggaran expected value, dan peraturan tersembunyi terselit dalam T&C.",
        "solution": "Expected value atas yuran, serta imbasan merah/kuning T&C untuk peraturan yang selalu menggagalkan orang.",
        "bot_commands": (("/propcalc YURAN SAIZ LULUS%", "expected value untuk satu challenge"),),
        "dashboard_views": (
            "Kalkulator penuh dengan kotak tampal T&C",
            "Laporan imbasan peraturan, bendera merah dan kuning disenaraikan",
            "Perbandingan firm yang disimpan",
        ),
        "upsell": "Audit PDF premium dan ramalan automatik.",
        "primary_why": "T&C yang panjang perlukan halaman; bot jawab ya-atau-tidak yang pantas.",
    },
    "bot-scam-detector": {
        "free_tier": "/audit tanpa had.",
        "problem": "Bot verifikasi palsu, pautan malware dan airdrop palsu melonjak sepanjang 2025.",
        "solution": "Skor sesuatu bot berdasarkan permintaan private key, promosi broker tanpa lesen dan ketiadaan pautan audit.",
        "bot_commands": (("/audit @nama_bot [teks]", "skor scam, penemuan utama, senarai semak 5 perkara"),),
        "dashboard_views": (
            "Borang tampal: username dan apa yang bot itu kata; jadual penemuan dengan sebab dan petikan",
            "Sejarah imbasan dengan pecahan skor (selepas log masuk)",
            "Senarai pantau bot untuk imbas semula sekali tekan",
            "Halaman kongsi awam untuk setiap imbasan",
        ),
        "upsell": "PRO imbasan automatik harian channel yang dilanggan serta pangkalan data malware.",
        "primary_why": "Ia mengaudit bot Telegram, jadi ia tinggal di tempat sasarannya berada.",
    },
    "gold-calendar": {
        "free_tier": "Kalendar penuh dan PDF, tak perlu log masuk.",
        "problem": "Trader abaikan musim emas — tetingkap Fed, cuti CME, kitaran barang kemas — dan spread yang melebar di sekitarnya.",
        "solution": "Kalendar volatiliti dan acara bulanan dengan tetingkap risiko spread ditanda.",
        "bot_commands": (
            ("/calendar", "acara seterusnya dan tingkah laku spread sebelum ini"),
            ("/calendar_alert", "push 30 minit sebelum setiap tetingkap"),
        ),
        "dashboard_views": (
            "Grid bulanan corak volatiliti dan tetingkap Fed",
            "Muat turun PDF suku tahun semasa",
            "Sejarah setiap acara — apa spread buat kali lepas",
        ),
        "upsell": "PRO bot alert masa nyata.",
        "primary_why": "Kalendar ialah halaman yang anda imbas; bot ialah push yang anda takkan terlepas.",
    },
    "copy-trade-audit": {
        "free_tier": "5 audit percuma.",
        "problem": "Influencer promosi copy-trading tanpa lesen; pengguna hilang modal kepada spread tersembunyi dan blowout.",
        "solution": "Semak lesen dan negative balance protection, kemudian kira kos spread tersembunyi.",
        "bot_commands": (("/copyaudit BROKER [SPREAD_PIP] [LOT_SEBULAN]", "regulator dalam jadual kami, tier-1 atau offshore, NBP, kos spread sebulan dan setahun"),),
        "dashboard_views": (
            "Borang audit dengan spread dan lot bulanan; jadual regulator dengan pautan daftar rasmi",
            "Sejarah audit dan senarai pantau broker (selepas log masuk)",
            "Model kos tersembunyi — kos spread sebulan dan setahun",
            "Halaman kongsi awam untuk setiap audit",
        ),
        "upsell": "PRO tanpa had serta laporan risiko portfolio mingguan.",
        "primary_why": "Ia mesti berjalan tepat ketika seseorang sedang di-pitch.",
    },
    "red-flag-scanner": {
        "free_tier": "Imbasan teks tanpa had.",
        "problem": "Penjual signal dakwa 100% tepat, padam trade rugi dan caj $30–$300 sebulan.",
        "solution": "Tanda ayat yang sentiasa mengiringi signal palsu, dan semak pautan audit yang disahkan.",
        "bot_commands": (("/scan TEKS", "skor 0–100, verdict, bendera utama dengan sebab setiap satu"),),
        "dashboard_views": (
            "Pengimbas dengan pitch penuh ditampal; jadual penemuan dengan bendera, sebab dan petikan",
            "Sejarah imbasan setiap penjual atau channel, dan senarai pantau (selepas log masuk)",
            "Halaman kongsi awam untuk setiap imbasan",
            "Kad skor mingguan untuk channel yang anda ikuti (PRO)",
        ),
        "upsell": "PRO imbasan automatik seluruh group dan kad skor mingguan.",
        "primary_why": "Pitch sampai dalam chat, jadi imbasan bermula di situ.",
    },
    "ib-revenue-calculator": {
        "free_tier": "Kalkulator penuh dan senarai semak pematuhan.",
        "problem": "IB affiliate berdepan peraturan payout yang kabur dan kos pematuhan yang tak boleh dianggar.",
        "solution": "Model hasil bersih selepas kos pematuhan, dengan garis masa payout dijelaskan.",
        "bot_commands": (("/ibcalc LOT KADAR", "anggaran pantas hasil bersih"),),
        "dashboard_views": (
            "Model hasil berbilang medan dengan garis masa payout",
            "Senarai semak pematuhan boleh muat turun",
            "Senario yang disimpan merentas broker",
        ),
        "upsell": "PRO ramalan bulanan automatik dan templat audit.",
        "primary_why": "Model berbilang medan dan muat turun dokumen; bot beri anggaran pantas.",
    },
    "influencer-audit": {
        "free_tier": "Audit tanpa had serta templat laporan kerugian.",
        "problem": "Berbilion hilang kepada scam pelaburan media sosial setiap tahun.",
        "solution": "Tuntut sejarah yang diaudit, bukan screenshot, dan tanda promosi broker tanpa lesen.",
        "bot_commands": (("/influencer @handle [teks]", "skor, kiraan pautan rujukan, empat perkara untuk dituntut"),),
        "dashboard_views": (
            "Arkib audit dengan halaman kongsi awam untuk setiap imbasan",
            "Penjana templat laporan kerugian untuk FTC / CFTC / IC3 / SC / BNM",
            "Jejak promosi broker — setiap pautan rujukan yang dijumpai",
            "Senarai pantau handle untuk audit semula (selepas log masuk)",
        ),
        "upsell": "PRO audit berkelompok dan channel amaran scam automatik.",
        "primary_why": "Viral secara semula jadi — audit ini dihantar balik ke group yang kongsi influencer itu.",
    },
    "rebate-auditor": {
        "free_tier": "Satu broker, satu bulan, laporan kekurangan penuh. Tanpa kad.",
        "problem": "Broker bayar rebate IB kurang melalui akaun yang digugurkan, kadar yang ditukar senyap dan simbol yang dikecualikan — dan hampir tiada siapa semak.",
        "solution": "Kira semula lot × kadar setiap simbol dan tier, banding dengan yang dibayar, dan hasilkan bukti sedia untuk pertikaian.",
        "bot_commands": (("/rebateaudit", "ringkasan penyelarasan terakhir anda, atau semakan pantas LOT KADAR DIBAYAR"), ("/rebatestatus", "jumlah kekurangan tempoh semasa")),
        "dashboard_views": ("Tampal atau muat naik CSV penyata broker dan log trade klien, kad kadar dengan kadar ikut simbol dan tier", "Jadual perbezaan boleh susun — kekurangan, akaun hilang, kadar ditukar senyap, simbol dikecualikan", "PDF pertikaian dengan kiraan setiap akaun, dan sejarah larian"),
        "upsell": "Penyelarasan automatik berbilang broker dan penjana surat pertikaian.",
        "primary_why": "Muat naik CSV, jadual perbezaan, PDF pertikaian; bot beritahu bila selesai.",
    },
    "churn-radar": {
        "free_tier": "10 klien dijejak, alert tanpa had.",
        "problem": "Hasil IB mati bila buku klien mati, dan tanda amarannya kelihatan berminggu-minggu sebelum payout jatuh.",
        "solution": "Skor setiap klien rujukan pada penyusutan volum, penggunaan margin, corak martingale dan hanyut dormansi.",
        "bot_commands": (("/ibchurn", "klien paling berisiko sekarang"), ("/ibchurn AKAUN", "butiran satu klien dan pecahan isyarat")),
        "dashboard_views": ("Gambaran buku disusun ikut kebarangkalian blow-up 30 hari", "Pecahan isyarat dan sejarah setiap klien", "Log intervensi — apa yang dicuba dan kesannya"),
        "upsell": "Klien tanpa had serta mesej susulan draf automatik.",
        "primary_why": "Buku klien ialah jadual yang anda kaji; bot beri amaran sebaik klien melepasi garisan.",
    },
    "broker-comparator": {
        "free_tier": "Jadual perbandingan awam dan arahan bot, terbuka sepenuhnya.",
        "problem": "Tiada siapa boleh lihat kos dagangan XAUUSD secara langsung merentas broker, jadi IB tak dapat buktikan laluannya yang paling murah.",
        "solution": "Spread, swap, komisen dan slippage secara langsung, disusun, dijadikan kad boleh kongsi yang membawa pautan IB sendiri.",
        "bot_commands": (("/goldspread", "kad perbandingan semasa"), ("/goldspread 1.0 overnight", "susunan kos untuk saiz lot dan tempoh pegangan")),
        "dashboard_views": ("Jadual perbandingan awam boleh diindeks — aset SEO", "Kalkulator kos untuk saiz lot dan tempoh pegangan", "Penjana kad berjenama rujukan"),
        "upsell": "Widget boleh benam berjenama sendiri.",
        "primary_why": "Jadual awam ialah aset SEO; bot hantar kad terus ke group.",
    },
    "link-attribution": {
        "free_tier": "3 pautan dijejak, paparan funnel penuh.",
        "problem": "Portal broker lapor pendaftaran tetapi tak pernah dari mana ia datang, jadi IB tak tahu channel mana yang membayar.",
        "solution": "Pautan pendek setiap channel yang menjejak post, klik, daftar, deposit pertama dan lot pertama.",
        "bot_commands": (("/newlink CHANNEL [URL]", "cipta pautan pendek dijejak"), ("/funnel", "klik, daftar, deposit, lot pertama hari ini")),
        "dashboard_views": ("Pengurus pautan dengan tag setiap channel", "Dashboard funnel dari klik hingga lot pertama", "Perbandingan channel dalam julat tarikh"),
        "upsell": "Pautan tanpa had serta LTV kohort dan payback.",
        "primary_why": "Pengurusan pautan dan funnel perlukan halaman; bot cipta pautan dan lapor harian.",
    },
    "drawdown-sentinel": {
        "free_tier": "1 akaun pada 1 firm, alert pelanggaran tanpa had.",
        "problem": "Kebanyakan challenge gagal kerana melanggar peraturan, bukan strategi lemah — garisan dilepasi sebelum trader sedar.",
        "solution": "Pantau daily loss, trailing drawdown, blackout berita, lot maksimum dan consistency mengikut pek peraturan firm, dan beri amaran sebelum pelanggaran.",
        "bot_commands": (("/sentinel link", "pautkan akaun dagangan"), ("/sentinel status", "jarak ke setiap garisan peraturan aktif"), ("/sentinel firm NAMA", "muat pek peraturan sesuatu firm")),
        "dashboard_views": ("Pautan akaun dan pilihan pek peraturan", "Tolok jarak-ke-pelanggaran langsung setiap peraturan", "Sejarah pelanggaran dan log hampir-langgar"),
        "upsell": "Berbilang akaun serta webhook tutup-semua automatik.",
        "primary_why": "Seluruh nilainya ialah push yang tiba beberapa saat sebelum garisan dilepasi.",
    },
    "monte-carlo-sim": {
        "free_tier": "1,000 simulasi setiap larian, larian tanpa had.",
        "problem": "Satu nombor expected value menyembunyikan hakikat bahawa set peraturan, bukan edge, yang menggagalkan orang.",
        "solution": "Simulasi laluan ekuiti terhadap set peraturan sebenar untuk kebarangkalian lulus dan kos-hingga-funded yang realistik.",
        "bot_commands": (("/simulate WINRATE RR RISIKO%", "kad ringkasan dengan kebarangkalian lulus dan kos dijangka"),),
        "dashboard_views": ("Carta kipas laluan ekuiti merentas simulasi", "Pemilih pek peraturan — daily DD, trailing DD, hari minimum, consistency", "Eksport PDF larian"),
        "upsell": "100k simulasi, pustaka pek peraturan penuh dan eksport PDF.",
        "primary_why": "Carta kipas dan PDF perlukan halaman; bot pulangkan kad ringkasan.",
    },
    "exposure-monitor": {
        "free_tier": "Snapshot atas permintaan, tanpa had.",
        "problem": "Lima trade terbuka selalunya satu pertaruhan berleverage, dan akaun tahu tepat ketika kluster itu bergerak.",
        "solution": "Kelompokkan posisi terbuka kepada satu angka risiko sebenar, termasuk kos rollover dan spread sesi.",
        "bot_commands": (("/exposure", "kluster semasa dan angka risiko sebenar"), ("/exposure warn", "hidupkan push amaran pendedahan berlebihan")),
        "dashboard_views": ("Peta haba korelasi buku terbuka", "Angka risiko sebenar dengan pecahan kluster", "Unjuran kos rollover dan spread sesi"),
        "upsell": "Pemantauan langsung dengan had pendedahan yang sedar peraturan prop.",
        "primary_why": "Pendedahan berlebihan ialah amaran yang perlu segera; peta haba menerangkannya kemudian.",
    },
    "tokenized-gold": {
        "free_tier": "Bacaan premium langsung dan semakan keselamatan wallet, tanpa had.",
        "problem": "PAXG dan XAUT hanyut dari spot, dan trader yang ambil payout dalam USDT terkena yuran chain, depeg dan address poisoning.",
        "solution": "Jejak premium dan diskaun terhadap spot XAU bersama yuran tebusan, kesegaran attestation dan kesihatan wallet payout.",
        "bot_commands": (("/paxg", "premium atau diskaun semasa berbanding spot XAU"), ("/walletcheck ALAMAT", "yuran chain, status depeg, semakan poisoning")),
        "dashboard_views": ("Carta premium/diskaun awam mengikut masa", "Kesegaran attestation rizab setiap token", "Laporan kesihatan wallet payout"),
        "upsell": "Alert arbitraj dan pemantauan wallet berterusan.",
        "primary_why": "Semakan depeg dan poisoning ialah alert; carta premium ialah halaman.",
    },
    "miner-divergence": {
        "free_tier": "Saringan mingguan, jadual penuh, tak perlu log masuk.",
        "problem": "Trader emas yang mahu pendedahan ekuiti tiada apa-apa yang menyaring pelombong terhadap logam itu sendiri.",
        "solution": "Saring GDX, GDXJ dan nama royalti untuk divergence beta, mampatan margin AISC dan risiko acara.",
        "bot_commands": (("/miners", "saringan divergence minggu ini"), ("/miners TICKER", "beta, margin AISC, earnings seterusnya untuk satu nama")),
        "dashboard_views": ("Jadual penyaring boleh susun merentas pelombong", "Carta divergence setiap nama terhadap spot emas", "Panel margin AISC dan risiko earnings/halt"),
        "upsell": "Alert harian dan backtesting.",
        "primary_why": "Penyaring boleh susun ialah jadual; bot bawa digest mingguan.",
    },
}
